export interface SamjhoItem{id:string;en:string;gu:string;answerEn:string;answerGu:string}
export const SAMJHO_IPO:SamjhoItem[]=[
{id:"ipo",en:"What is an IPO?",gu:"IPO શું છે?",answerEn:"An Initial Public Offering (IPO) is when a company offers its shares to the public for the first time. After listing, those shares can trade on the exchange.",answerGu:"IPO એટલે કંપની પહેલી વાર પોતાના શેર જાહેર રોકાણકારોને ખરીદવા માટે આપે છે. લિસ્ટિંગ પછી આ શેર બજારમાં ખરીદ-વેચાણ થઈ શકે છે."},
{id:"price-band",en:"What is a price band?",gu:"પ્રાઇસ બેન્ડ શું છે?",answerEn:"The price band is the range (lower to upper price) within which investors can bid.",answerGu:"પ્રાઇસ બેન્ડ એ ભાવની શ્રેણી છે (નીચો ભાવથી ઉપરનો ભાવ) જેમાં રોકાણકારો બોલી લગાવે છે."},
{id:"lot",en:"What is lot size?",gu:"લોટ સાઇઝ શું છે?",answerEn:"Shares must be applied for in fixed lots. You cannot apply for fewer shares than one lot.",answerGu:"શેર નિશ્ચિત લોટમાં જ અરજી થાય છે. એક લોટથી ઓછા શેર માટે અરજી ન થઈ શકે."},
{id:"min",en:"What is minimum investment?",gu:"લઘુત્તમ અરજી શું છે?",answerEn:"Minimum investment is usually one lot × the upper price band. If an official minimum is published, use that.",answerGu:"લઘુત્તમ અરજી સામાન્ય રીતે એક લોટ × ઉપરનો ભાવ પટ્ટો હોય છે. સત્તાવાર રકમ હોય તો તે વાપરો."},
{id:"gmp",en:"What is GMP?",gu:"GMP શું છે?",answerEn:"GMP is an unofficial grey-market premium before listing. It is not from NSE, BSE or SEBI and does not guarantee listing gains.",answerGu:"GMP લિસ્ટિંગ પહેલાંનો અનૌપચારિક ગ્રે-માર્કેટ પ્રીમિયમ છે. તે NSE, BSE કે SEBIનો આંકડો નથી અને લિસ્ટિંગ નફાની ખાતરી આપતો નથી."},
{id:"sub",en:"What is subscription?",gu:"સબ્સ્ક્રિપ્શન શું છે?",answerEn:"Subscription shows how many times the offered shares were bid for. 2.00x means bids were twice the shares reserved.",answerGu:"સબ્સ્ક્રિપ્શન બતાવે છે કે ફાળવેલા શેરની સામે કેટલી વાર બોલી આવી. 2.00 ગણું એટલે બમણી બોલી."},
{id:"qib",en:"Who is a QIB?",gu:"QIB કોણ છે?",answerEn:"Qualified Institutional Buyers include institutions such as mutual funds, insurers and FPIs.",answerGu:"QIBમાં મ્યુચ્યુઅલ ફંડ, વીમા કંપનીઓ અને FPI જેવી સંસ્થાઓ આવે છે."},
{id:"nii",en:"Who is an NII / HNI?",gu:"NII / HNI કોણ છે?",answerEn:"Non-Institutional Investors bid above the retail limit. Exact bands follow current SEBI rules.",answerGu:"NII એ રિટેલ મર્યાદા કરતાં વધુની અરજી કરનારા રોકાણકારો છે. ચોક્કસ મર્યાદા SEBI નિયમ પ્રમાણે હોય છે."},
{id:"retail",en:"Who is Retail?",gu:"Retail કોણ છે?",answerEn:"Retail Individual Investors apply within the SEBI retail cap and may use UPI/cut-off.",answerGu:"Retail રોકાણકારો SEBIની રિટેલ મર્યાદા સુધી અરજી કરે છે અને UPI/કટ-ઑફ વાપરી શકે છે."},
{id:"fresh",en:"What is a Fresh Issue?",gu:"Fresh Issue શું છે?",answerEn:"A fresh issue creates new shares and the money goes to the company for stated objects.",answerGu:"Fresh Issueમાં નવા શેર ઉભા થાય છે અને પૈસા કંપનીને પ્રોસ્પેક્ટસમાં જણાવેલા ઉદ્દેશો માટે મળે છે."},
{id:"ofs",en:"What is OFS?",gu:"OFS શું છે?",answerEn:"Offer for Sale means existing shareholders sell shares; proceeds go to those sellers.",answerGu:"OFSમાં હાલના શેરધારકો પોતાના શેર વેચે છે અને પૈસા તેમને મળે છે."},
{id:"size",en:"What is issue size?",gu:"ઇશ્યૂ સાઇઝ શું છે?",answerEn:"Issue size is the total offer value — fresh issue plus OFS.",answerGu:"ઇશ્યૂ સાઇઝ એ કુલ ઑફરની કિંમત છે — Fresh Issue વત્તા OFS."},
{id:"allot",en:"What is allotment?",gu:"ફાળવણી શું છે?",answerEn:"After the issue closes, the registrar allots shares under applicable rules. Check the registrar only after the allotment date.",answerGu:"ઇશ્યૂ બંધ થયા પછી રજિસ્ટ્રાર નિયમ મુજબ શેર ફાળવે છે. ફાળવણી તારીખ પછી જ રજિસ્ટ્રાર પર સ્ટેટસ ચકાસો."},
{id:"listing",en:"What is listing?",gu:"લિસ્ટિંગ શું છે?",answerEn:"Listing is when allotted shares start trading on NSE and/or BSE. GMP does not guarantee the listing price.",answerGu:"લિસ્ટિંગ એટલે ફાળવાયેલા શેર NSE/BSE પર ટ્રેડ થવા લાગે. GMP લિસ્ટિંગ ભાવની ખાતરી આપતું નથી."}
];