export type IpoStatus="OPEN"|"UPCOMING"|"CLOSED";
export type IpoBoard="Mainboard"|"SME";
export type FieldConfidence="official"|"secondary"|"unofficial"|"derived"|"unavailable";
export type SubscriptionCategoryName="QIB"|"NII"|"bNII"|"sNII"|"Retail"|"Employee"|"Other"|"Total";
export interface FieldSource{source:string;url:string|null;timestamp:string|null;confidence:FieldConfidence}
export interface SubscriptionRow{category:SubscriptionCategoryName;multiple:number|null;offeredShares:number|null;bids:number|null;amountCr:number|null;source:string|null;timestamp:string|null}
export interface FinancialYear{year:string;revenue:number|null;ebitda:number|null;pat:number|null;eps:number|null;debt:number|null;netWorth:number|null;assets:number|null;roe:number|null;roce:number|null;source:string|null}
export interface GmpPoint{rs:number;pct:number|null;asOf:string;source:string;url:string|null}
export interface IpoDocument{label:string;url:string;source:string}
export interface IssueQuota{label:string;shares:number|null;pctOfIssue:number|null}
export interface IpoRecord{
id:string;name:string;normalizedName:string;type:IpoBoard;symbol:string|null;nseSymbol:string|null;bseSymbol:string|null;bseScripCode:string|null;exchange:"NSE India"|"BSE India"|"BOTH"|"UNKNOWN";exchanges:string[];
openDate:string|null;closeDate:string|null;listingDate:string|null;allotmentDate:string|null;refundDate:string|null;dematCreditDate:string|null;
issueSize:number|null;minSubscription:number|null;verifiedMinApplication:number|null;subscription:number|null;subscriptionAmount:number|null;subscriptionSource:string|null;subscriptionTimestamp:string|null;subscriptionCategories:SubscriptionRow[];
gmpPct:number|null;gmpRs:number|null;gmpSources:Array<{source:string;url:string|null;pct:number|null;rs:number|null;asOf:string|null}>;gmpVerifiedSources:string[];gmpHistory:GmpPoint[];
city:string|null;state:string|null;business:string|null;businessModel:string|null;sector:string|null;products:string[];services:string[];businessLocations:string[];registeredOffice:string|null;corporateOffice:string|null;promoters:string[];segments:string[];competitors:string[];customerType:string|null;customerConcentration:string|null;customerCategories:string[];industriesServed:string[];geographicPresence:string[];domesticMarket:boolean|null;exportMarket:boolean|null;b2b:boolean|null;b2c:boolean|null;countries:Array<{country:string;business:string;salesPct:number|null}>;countryCount:number|null;
revenueSources:Array<{segment:string;amount:number|null;percentage:number|null}>;domesticRevenuePercent:number|null;exportRevenuePercent:number|null;revenues:Array<{year:string;value:number|null}>;profits:Array<{year:string;value:number|null}>;eps:Array<{year:string;value:number|null}>;financials:FinancialYear[];
priceBand:string|null;priceLow:number|null;priceHigh:number|null;lotSize:number|null;faceValue:number|null;sharesOffered:number|null;offeredToPublic:number|null;retailShares:number|null;qibShares:number|null;niiShares:number|null;bniiShares:number|null;sniiShares:number|null;employeeShares:number|null;anchorShares:number|null;quotas:IssueQuota[];
freshIssue:number|null;freshIssueShares:number|null;offerForSale:number|null;offerForSaleShares:number|null;issueType:string|null;objects:string[];risks:string[];promoterHolding:number|null;postIssuePromoterHolding:number|null;
registrar:string|null;registrarAddress:string|null;registrarEmail:string|null;registrarPhone:string|null;registrarWebsite:string|null;allotmentCheckUrl:string|null;leadManagers:string[];sponsorBank:string|null;marketMaker:string|null;scsbListUrl:string|null;
officialWebsite:string|null;prospectusUrl:string|null;rhpUrl:string|null;drhpUrl:string|null;prospectusType:"DRHP"|"RHP"|"Prospectus"|"Abridged Prospectus"|null;documents:IpoDocument[];nsePageUrl:string|null;bsePageUrl:string|null;companyIpoUrl:string|null;sebiUrl:string|null;chittorgarhUrl:string|null;moneycontrolUrl:string|null;detailSource:string|null;verifiedSources:string[];sourceUrls:string[];fieldSources:Record<string,FieldSource>;rhpStatus:"NOT_FOUND"|"DISCOVERED_UNPARSED"|"PARSED"|"PARSE_FAILED";verifiedAt:string;errors:string[];
}
export function emptyIpo(partial:Partial<IpoRecord>&Pick<IpoRecord,"id"|"name">):IpoRecord{return{normalizedName:"",type:"Mainboard",symbol:null,nseSymbol:null,bseSymbol:null,bseScripCode:null,exchange:"UNKNOWN",exchanges:[],openDate:null,closeDate:null,listingDate:null,allotmentDate:null,refundDate:null,dematCreditDate:null,issueSize:null,minSubscription:null,verifiedMinApplication:null,subscription:null,subscriptionAmount:null,subscriptionSource:null,subscriptionTimestamp:null,subscriptionCategories:[],gmpPct:null,gmpRs:null,gmpSources:[],gmpVerifiedSources:[],gmpHistory:[],city:null,state:null,business:null,businessModel:null,sector:null,products:[],services:[],businessLocations:[],registeredOffice:null,corporateOffice:null,promoters:[],segments:[],competitors:[],customerType:null,customerConcentration:null,customerCategories:[],industriesServed:[],geographicPresence:[],domesticMarket:null,exportMarket:null,b2b:null,b2c:null,countries:[],countryCount:null,revenueSources:[],domesticRevenuePercent:null,exportRevenuePercent:null,revenues:[],profits:[],eps:[],priceBand:null,priceLow:null,priceHigh:null,lotSize:null,faceValue:null,sharesOffered:null,offeredToPublic:null,retailShares:null,qibShares:null,niiShares:null,bniiShares:null,sniiShares:null,employeeShares:null,anchorShares:null,quotas:[],freshIssue:null,freshIssueShares:null,offerForSale:null,offerForSaleShares:null,issueType:null,objects:[],risks:[],promoterHolding:null,postIssuePromoterHolding:null,registrar:null,registrarAddress:null,registrarEmail:null,registrarPhone:null,registrarWebsite:null,allotmentCheckUrl:null,leadManagers:[],sponsorBank:null,marketMaker:null,scsbListUrl:null,officialWebsite:null,prospectusUrl:null,rhpUrl:null,drhpUrl:null,prospectusType:null,documents:[],nsePageUrl:null,bsePageUrl:null,companyIpoUrl:null,sebiUrl:null,chittorgarhUrl:null,moneycontrolUrl:null,detailSource:null,verifiedSources:[],sourceUrls:[],fieldSources:{},rhpStatus:"NOT_FOUND",verifiedAt:new Date().toISOString(),errors:[],...partial};}
