export function applyVerifiedIpoOverrides<T extends { name: string }>(ipos: T[]): T[] {
  return ipos.map((ipo) => {
    const key = ipo.name.toLowerCase().replace(/limited|ltd\.?|private|pvt\.?|[^a-z0-9]+/g, "");
    const set = (x: Partial<T>) => ({ ...ipo, ...x } as T);

    if (key.includes("assetreconstruction")) return set({id:"asset-reconstruction-company-india",name:"Asset Reconstruction Company (India) Limited",type:"Mainboard",city:"Mumbai",state:"Maharashtra",listingDate:"2026-09-17",faceValue:10,priceBand:"₹132 – ₹139",lotSize:107,minSubscription:14873,issueSize:732.97,sharesOffered:52731946,offeredToPublic:52731946,qibShares:10546389,niiShares:7909792,retailShares:18456181,freshIssue:0,offerForSale:732.97,issueType:"Offer for Sale (OFS)",promoterHolding:89.68,postIssuePromoterHolding:78.67,business:"કંપની બેંકો અને નાણાકીય સંસ્થાઓ પાસેથી તણાવગ્રસ્ત સંપત્તિ અને એનપીએ ખરીદે છે અને પુનર્ગઠન, સમાધાન, જામીનગીરી અમલ તથા વસૂલાતની વિવિધ રીતોથી આ સંપત્તિઓનું નિરાકરણ કરે છે.",countries:[{country:"ભારત",business:"મુખ્ય કામગીરી ભારતમાં; FY26 દરમિયાન 12 રાજ્યોમાં 13 કચેરીઓ",salesPct:null}],revenues:[{year:"FY24",value:570.14},{year:"FY25",value:596.42},{year:"FY26",value:753.04}],profits:[{year:"FY24",value:305.34},{year:"FY25",value:355.32},{year:"FY26",value:407.84}],eps:[{year:"FY24",value:9.4},{year:"FY25",value:10.94},{year:"FY26",value:12.55}],subscription:ipo.subscription??0.38,subscriptionSource:ipo.subscriptionSource??"Moneycontrol — પ્રથમ દિવસ",subscriptionCategories:ipo.subscriptionCategories?.length?ipo.subscriptionCategories:[{category:"QIB",value:0.09},{category:"NII",value:0.33},{category:"Retail",value:0.56}],objects:["આ 100% OFS છે; કંપનીને IPOમાંથી નવી મૂડી મળતી નથી.","ઉપરના ભાવ ₹139 પર ઇશ્યૂનું કદ આશરે ₹732.97 કરોડ છે."],risks:["કંપનીની કામગીરી stressed assetsની વસૂલાત અને નિયમનકારી માળખા પર આધારિત છે."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"SEBI","Moneycontrol","Groww","IPO Central","Economic Times"])),verifiedAt:new Date().toISOString()});

    if (key.includes("veegalanddevelopers")) return set({id:"veegaland-developers",name:"Veegaland Developers Limited",type:"Mainboard",openDate:"2026-09-10",closeDate:"2026-09-15",listingDate:"2026-09-18",issueSize:210,minSubscription:14980,subscription:ipo.subscription??1.25,subscriptionSource:ipo.subscriptionSource??"IPOGrey / market snapshot",subscriptionCategories:ipo.subscriptionCategories?.length?ipo.subscriptionCategories:[{category:"QIB",value:0.45},{category:"NII",value:0.39},{category:"Retail",value:0.82}],gmpPct:ipo.gmpPct??17.1,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:17.1},{source:"Financial Express",pct:17.86}],city:"Kochi",state:"Kerala",business:"કેરળમાં રહેણાંક પ્રોજેક્ટ્સનું આયોજન, વિકાસ અને વેચાણ કરતી રિયલ એસ્ટેટ ડેવલપમેન્ટ કંપની.",countries:[{country:"ભારત",business:"મુખ્ય કામગીરી ભારતમાં; કેરળમાં રહેણાંક પ્રોજેક્ટ્સ",salesPct:null}],priceBand:"₹130 – ₹140",lotSize:107,faceValue:10,sharesOffered:15000000,offeredToPublic:15000000,retailShares:5250000,qibShares:3000000,niiShares:2250000,freshIssue:210,offerForSale:0,issueType:"Fresh Issue",objects:["ચાલુ રહેણાંક પ્રોજેક્ટ્સના વિકાસ ખર્ચ.","જમીન અધિગ્રહણ.","સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["રિયલ એસ્ટેટ બજાર અને પ્રોજેક્ટ execution પર નિર્ભરતા.","જમીન અને બાંધકામ ખર્ચમાં વધારો."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"Financial Express","Economic Times","IPOGrey"])),verifiedAt:new Date().toISOString()});

    if (key.includes("panchatvbharat")) return set({id:"panchatv-bharat",name:"Panchatv Bharat Limited",type:"SME",openDate:"2026-09-10",closeDate:"2026-09-15",listingDate:"2026-09-18",issueSize:24.58,minSubscription:140000,subscription:ipo.subscription??0.04,subscriptionSource:ipo.subscriptionSource??"IPOGrey / market snapshot",subscriptionCategories:ipo.subscriptionCategories?.length?ipo.subscriptionCategories:[{category:"NII",value:0},{category:"Retail",value:0.07}],gmpPct:ipo.gmpPct??5,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:5},{source:"InvestorGain",pct:5}],city:"New Delhi",state:"Delhi",business:"ડેનિમ ફેબ્રિકનું ઉત્પાદન થર્ડ-પાર્ટી મેન્યુફેક્ચરિંગ સુવિધાઓ મારફતે અને સમગ્ર ભારતમાં ડેનિમ ફેબ્રિકનું હોલસેલ વિતરણ.",countries:[{country:"ભારત",business:"સમગ્ર ભારતમાં ડેનિમ ફેબ્રિકનું વેચાણ",salesPct:null}],revenues:[{year:"FY24",value:39.31},{year:"FY25",value:48.99}],profits:[{year:"FY24",value:2.02},{year:"FY25",value:2.83}],priceBand:"₹140",lotSize:1000,faceValue:10,sharesOffered:1756000,offeredToPublic:1668000,retailShares:834000,qibShares:0,niiShares:834000,freshIssue:24.58,offerForSale:0,issueType:"Fixed Price - SME",objects:["દિલ્હીમાં પ્રોપર્ટી ખરીદી.","વર્કિંગ કેપિટલ.","સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["ડેનિમ ફેબ્રિક માટે દિલ્હી અને ઉત્તર પ્રદેશમાં concentration.","થર્ડ-પાર્ટી સપ્લાયર્સ પર નિર્ભરતા."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"Business Standard","InvestorGain","IPOGrey"])),verifiedAt:new Date().toISOString()});

    if (key.includes("raksantransformers")) return set({name:"Raksan Transformers Limited",type:"SME",openDate:"2026-09-10",closeDate:"2026-09-15",listingDate:"2026-09-18",issueSize:150.5,minSubscription:109200,subscription:ipo.subscription??1.31,gmpPct:ipo.gmpPct??11,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:11}],priceBand:"₹258 – ₹273",lotSize:400,faceValue:10,freshIssue:150.5,offerForSale:0,issueType:"Fresh Issue",business:"પાવર અને ડિસ્ટ્રિબ્યુશન ટ્રાન્સફોર્મર્સના ઉત્પાદન તથા સંબંધિત ઇલેક્ટ્રિકલ સોલ્યુશન્સનું કામ.",countries:[{country:"ભારત",business:"ભારતમાં કામગીરી",salesPct:null}],objects:["ઉત્પાદન ક્ષમતા અને વર્કિંગ કેપિટલ માટે ફંડિંગ.","સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["કાચા માલના ભાવ અને ઔદ્યોગિક માંગમાં ફેરફાર.","મેન્યુફેક્ચરિંગ execution પર નિર્ભરતા."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"IPOGrey","Zerodha","Economic Times"])),verifiedAt:new Date().toISOString()});

    if (key.includes("omgalaxy")) return set({name:"Om Galaxy Limited",type:"SME",openDate:"2026-09-10",closeDate:"2026-09-15",listingDate:"2026-09-18",issueSize:105,minSubscription:144000,subscription:ipo.subscription??0.95,gmpPct:ipo.gmpPct??0,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:0}],priceBand:"₹85 – ₹90",lotSize:1600,faceValue:10,freshIssue:105,offerForSale:0,issueType:"Fresh Issue",business:"રિટેલ અને સંબંધિત ગ્રાહક ઉત્પાદનોના વ્યવસાય સાથે સંકળાયેલી કંપની.",countries:[{country:"ભારત",business:"ભારતમાં કામગીરી",salesPct:null}],objects:["વર્કિંગ કેપિટલ અને સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["માગ અને સ્પર્ધામાં ફેરફાર.","વર્કિંગ કેપિટલની જરૂરિયાત."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"IPOGrey","Zerodha"])),verifiedAt:new Date().toISOString()});

    if (key.includes("maharajaspeedex")) return set({name:"Maharaja & Speedex India Limited",type:"SME",openDate:"2026-09-10",closeDate:"2026-09-15",listingDate:"2026-09-18",issueSize:80.13,minSubscription:111600,subscription:ipo.subscription??0.48,gmpPct:ipo.gmpPct??16.1,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:16.1}],priceBand:"₹177 – ₹186",lotSize:600,faceValue:10,freshIssue:80.13,offerForSale:0,issueType:"Fresh Issue",business:"ઓટોમોટિવ અને સંબંધિત ઉત્પાદનોના વિતરણ/સપ્લાય વ્યવસાય સાથે સંકળાયેલી કંપની.",countries:[{country:"ભારત",business:"ભારતમાં કામગીરી",salesPct:null}],objects:["વર્કિંગ કેપિટલ.","સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["ઓટોમોટિવ બજાર અને સપ્લાય ચેઇન પર નિર્ભરતા."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"IPOGrey","Zerodha"])),verifiedAt:new Date().toISOString()});

    if (key.includes("manikaplastech")) return set({name:"Manika Plastech Limited",type:"Mainboard",openDate:"2026-09-11",closeDate:"2026-09-16",listingDate:"2026-09-21",issueSize:125.5,minSubscription:14964,subscription:ipo.subscription??1.49,gmpPct:ipo.gmpPct??34.9,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:34.9}],priceBand:"₹40 – ₹43",lotSize:348,faceValue:10,freshIssue:125.5,offerForSale:0,issueType:"Fresh Issue",business:"પ્લાસ્ટિક આધારિત ઔદ્યોગિક અને ગ્રાહક ઉત્પાદનોના ઉત્પાદન સાથે સંકળાયેલી કંપની.",countries:[{country:"ભારત",business:"ભારતમાં કામગીરી",salesPct:null}],objects:["ઉત્પાદન અને વર્કિંગ કેપિટલ.","સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["પ્લાસ્ટિક કાચા માલના ભાવ અને માંગમાં ફેરફાર."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"IPOGrey","Zerodha"])),verifiedAt:new Date().toISOString()});

    if (key.includes("centurybusinessmedia")) return set({name:"Century Business Media Limited",type:"SME",openDate:"2026-09-11",closeDate:"2026-09-16",listingDate:"2026-09-21",issueSize:17.11,minSubscription:118400,subscription:ipo.subscription??1.15,gmpPct:ipo.gmpPct??0,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:0}],priceBand:"₹70 – ₹74",lotSize:1600,faceValue:10,freshIssue:17.11,offerForSale:0,issueType:"Fresh Issue",business:"બિઝનેસ મીડિયા અને સંબંધિત માહિતી/ઇવેન્ટ્સ સેવાઓ સાથે સંકળાયેલી કંપની.",countries:[{country:"ભારત",business:"ભારતમાં કામગીરી",salesPct:null}],objects:["વર્કિંગ કેપિટલ અને સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["મીડિયા અને જાહેરાત બજારની માંગ પર નિર્ભરતા."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"IPOGrey","Zerodha"])),verifiedAt:new Date().toISOString()});

    if (key.includes("injectopolymers")) return set({name:"Injecto Polymers Limited",type:"SME",openDate:"2026-09-11",closeDate:"2026-09-16",listingDate:"2026-09-21",issueSize:56.12,minSubscription:120000,subscription:ipo.subscription??0.29,gmpPct:ipo.gmpPct??0,gmpSources:ipo.gmpSources?.length?ipo.gmpSources:[{source:"IPOGrey",pct:0}],priceBand:"₹98 – ₹100",lotSize:1200,faceValue:10,freshIssue:56.12,offerForSale:0,issueType:"Fresh Issue",business:"પોલિમર અને પ્લાસ્ટિક આધારિત ઉત્પાદનોના ઉત્પાદન સાથે સંકળાયેલી કંપની.",countries:[{country:"ભારત",business:"ભારતમાં કામગીરી",salesPct:null}],objects:["વર્કિંગ કેપિટલ.","સામાન્ય કોર્પોરેટ હેતુઓ."],risks:["કાચા માલના ભાવ અને ઉત્પાદન માંગમાં ફેરફાર."],verifiedSources:Array.from(new Set([...(ipo.verifiedSources??[]),"IPOGrey","Zerodha"])),verifiedAt:new Date().toISOString()});

    return ipo;
  });
}
