import { createServerFn } from "@tanstack/react-start";
import { applyVerifiedIpoOverrides } from "./ipo-overrides";

type Ipo={id:string;name:string;type:"Mainboard"|"SME";openDate:string|null;closeDate:string|null;listingDate:string|null;issueSize:number|null;minSubscription:number|null;subscription:number|null;subscriptionSource:string|null;subscriptionCategories:{category:string;value:number|null}[];gmpPct:number|null;gmpSources:{source:string;pct:number|null}[];city:string|null;state:string|null;business:string|null;countries:{country:string;business:string;salesPct:number|null}[];revenues:{year:string;value:number|null}[];profits:{year:string;value:number|null}[];eps:{year:string;value:number|null}[];priceBand:string|null;lotSize:number|null;faceValue:number|null;sharesOffered:number|null;offeredToPublic:number|null;retailShares:number|null;qibShares:number|null;niiShares:number|null;freshIssue:number|null;offerForSale:number|null;issueType:string|null;objects:string[];risks:string[];promoterHolding:number|null;postIssuePromoterHolding:number|null;moneycontrolUrl:string|null;detailSource:string|null;verifiedSources:string[];sourceUrls:string[];verifiedAt:string};
type SamcoIpo={id:string;slug:string;company_name:string;type:string;company_profile:string;issue_type:string;issue_open:string;issue_close:string;listed_date:string;face_value:string;price_band:string;bid_lot:string;minimum_order:string;listing:string;issue_size:string;fresh_issue:string;ofs:string;obj_issue:string;key_strengths:string;risks:string;RHP_url:string;knowledge_center_url:string};
const ENDPOINT="https://www.samco.in/ipo/get_upcoming_data/";
const cache=new Map<string,{expires:number;value:Ipo[]}>();
function n(v:unknown){const x=Number(String(v??"").replace(/,/g,""));return Number.isFinite(x)?x:null}
function clean(v:string){return String(v??"").replace(/<[^>]+>/g," ").replace(/\\r|\\n/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/\\\//g,"/").replace(/\\"/g,'"').replace(/\\s+/g," ").trim()}
function date(v:string|null){return v&&/^\\d{4}-\\d{2}-\\d{2}/.test(v)?v.slice(0,10):null}
function band(v:string){const m=String(v??"").match(/(?:Rs|₹)\\s*([\\d,.]+)\\s*(?:to|-|–)\\s*(?:Rs|₹)?\\s*([\\d,.]+)/i);return m?`₹${n(m[1])?.toLocaleString("en-IN")} – ₹${n(m[2])?.toLocaleString("en-IN")}`:null}
function upper(v:string){const m=String(v??"").match(/(?:Rs|₹)\\s*[\\d,.]+\\s*(?:to|-|–)\\s*(?:Rs|₹)?\\s*([\\d,.]+)/i);return n(m?.[1])}
function slugId(v:string){return String(v).toLowerCase().replace(/limited|ltd\\.?|private|pvt\\.?|ipo/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function blank(x:SamcoIpo):Ipo{const p=clean(x.company_profile);const cityMatch=p.match(/\\b(Mumbai|Surat|Ahmedabad|Pune|Bengaluru|Bangalore|Chennai|Delhi|Hyderabad|Kolkata|Vadodara|Rajkot|Jaipur|Noida|Gurugram|Indore)\\b/i);const stateMatch=p.match(/\\b(Maharashtra|Gujarat|Karnataka|Tamil Nadu|Delhi|Telangana|West Bengal|Rajasthan|Haryana|Uttar Pradesh|Madhya Pradesh)\\b/i);const lot=n(x.bid_lot),price=band(x.price_band),up=upper(x.price_band);return{id:slugId(x.company_name||x.slug),name:x.company_name,type:/SME/i.test(x.type)||/SME/i.test(x.listing)?"SME":"Mainboard",openDate:date(x.issue_open),closeDate:date(x.issue_close),listingDate:date(x.listed_date),issueSize:n(String(x.issue_size).replace(/Crores?/i,"")),minSubscription:lot!==null&&up!==null?lot*up:null,subscription:null,subscriptionSource:null,subscriptionCategories:[],gmpPct:null,gmpSources:[],city:cityMatch?.[1]??null,state:stateMatch?.[1]??null,business:p.slice(0,2200)||null,countries:[],revenues:[],profits:[],eps:[],priceBand:price,lotSize:lot,faceValue:n(String(x.face_value).match(/[\\d,.]+/)?.[0]),sharesOffered:null,offeredToPublic:null,retailShares:null,qibShares:null,niiShares:null,freshIssue:n(String(x.fresh_issue).replace(/Crores?/i,"")),offerForSale:n(String(x.ofs).replace(/Crores?/i,"")),issueType:x.issue_type||null,objects:x.obj_issue?[clean(x.obj_issue)]:[],risks:x.risks?[clean(x.risks)]:[],promoterHolding:null,postIssuePromoterHolding:null,moneycontrolUrl:null,detailSource:"Samco live structured IPO feed",verifiedSources:["Samco"],sourceUrls:["https://www.samco.in/ipo"],verifiedAt:new Date().toISOString()}}
async function getJson(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (compatible; Artha-market/3.0)",Accept:"application/json,text/plain,*/*"},cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
async function loadSamco(){const pages=await Promise.all(Array.from({length:16},(_,i)=>getJson(`${ENDPOINT}${i+1}`).catch(()=>null)));const all:SamcoIpo[]=[];for(const p of pages){const rows=p?.data?.upcoming_ipo;if(Array.isArray(rows))all.push(...rows)}const today=new Date().toISOString().slice(0,10);const map=new Map<string,SamcoIpo>();for(const x of all){if(!x?.company_name||!x.issue_close||x.issue_close<today)continue;map.set(slugId(x.company_name),x)}return applyVerifiedIpoOverrides([...map.values()].map(blank).sort((a,b)=>(a.closeDate??"").localeCompare(b.closeDate??"")))}
export const fetchOpenIposLive=createServerFn({method:"GET"}).handler(async()=>{const hit=cache.get("live");if(hit&&hit.expires>Date.now())return hit.value;const data=await loadSamco();cache.set("live",{expires:Date.now()+60000,value:data});return data});
