import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

type Ipo={id:string;name:string;type:"Mainboard"|"SME";closeDate:string|null;minSubscription:number|null;subscription:number|null;subscriptionSource:string|null;gmpPct:number|null;gmpSources:{source:string;pct:number|null}[];city:string|null;state:string|null;business:string|null;countries:{country:string;business:string;salesPct:number|null}[];profits:{year:string;value:number|null}[];priceBand:string|null;lotSize:number|null;verifiedAt:string};
const GROWw_DASHBOARD="https://groww.in/ipo";
const GROWW_SUBSCRIPTION="https://groww.in/ipo/subscription";
const ANGEL_UPCOMING="https://www.angelone.in/upcoming-ipo";
const GMP_SOURCE_URLS=(id:string)=>({"IPO Watch":`https://ipowatch.in/${id}-ipo-gmp-grey-market-premium/`,"IPO Central":`https://ipocentral.in/${id}-ipo-gmp-price-allotment/`,"GMP IPO Watch":`https://www.gmpipowatch.in/ipo/${id}`,"InvestorGain":`https://www.investorgain.com/gmp/${id}-ipo-gmp/`});
const cache=new Map<string,{exp:number;value:Ipo[]}>();
const UA="Mozilla/5.0 (compatible; Artha-market/1.0)";
async function getHtml(url:string,timeoutMs=15000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch(url,{headers:{"User-Agent":UA,Accept:"text/html,application/xhtml+xml,application/json","Accept-Language":"en-US,en;q=0.9"},cache:"no-store",signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
function clean(h:string){return h.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/g,"&").replace(/&#8377;|&#x20b9;/gi,"₹").replace(/&ndash;|&mdash;/gi,"-").replace(/\s+/g," ").trim()}
function norm(s:string){return s.toLowerCase().replace(/&amp;/g,"and").replace(/limited|ltd\.?|private|pvt\.?|ipo|inc\.?/g,"").replace(/[^a-z0-9]+/g," ").trim()}
function num(v:unknown){const n=Number(String(v??"").replace(/,/g,""));return Number.isFinite(n)?n:null}
function idFor(name:string){return norm(name).replace(/\s+/g,"-")}
function parseDate(s:string){let m=s.match(/(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})/);if(!m)m=s.match(/([A-Za-z]{3,9})\s+(\d{1,2}),?\s+(\d{4})/);if(!m)return null;const months:Record<string,string>={jan:"01",feb:"02",mar:"03",apr:"04",may:"05",jun:"06",jul:"07",aug:"08",sep:"09",oct:"10",nov:"11",dec:"12"};const mo=months[m[2]?.slice(0,3).toLowerCase()]??months[m[1]?.slice(0,3).toLowerCase()];const day=m[2]?.match(/^\d/) ? m[1] : m[2], year=m[3];return mo?`${year}-${mo}-${String(Number(day)).padStart(2,"0")}`:null}
function parsePriceBand(s:string){const m=s.match(/₹\s*([\d,.]+)\s*(?:-|–|to)\s*₹?\s*([\d,.]+)/i);return m?`₹${m[1]} – ₹${m[2]}`:s.match(/₹\s*([\d,.]+)/)?.[0]??null}
function extractGmp(text:string){const t=clean(text);const labelled=t.match(/(?:Current GMP Status|Live GMP|Current GMP|GMP Today)[\s\S]{0,180}?₹\s*(-?[\d,]+(?:\.\d+)?)/i);if(labelled)return num(labelled[1]);const heading=t.match(/IPO GMP Today[\s\S]{0,260}?(?:\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}|\d{1,2}\s+[A-Za-z]+)[\s\S]{0,80}?₹\s*(-?[\d,]+(?:\.\d+)?)/i);return heading?num(heading[1]):null}
function median(values:number[]){const a=[...values].sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function parseDashboardOpen(html:string){const rows=[...html.matchAll(/<tr\b[\s\S]*?<\/tr>/gi)].map(m=>clean(m[0])).filter(Boolean);const out:Ipo[]=[];const seen=new Set<string>();for(const row of rows){const dates=[...row.matchAll(/\d{1,2}\s+[A-Za-z]{3}\s+\d{4}/g)].map(m=>m[0]);if(dates.length<2)continue;const type:/SME/i.test(row)?"SME":"Mainboard";const before=row.split(/\d{1,2}\s+[A-Za-z]{3}\s+\d{4}/)[0].replace(/Company Name|Type|Open Date|Close Date/gi," ").trim();const name=before.replace(/\b(Mainboard|SME)\b/gi," ").replace(/Image:\s*/i,"").replace(/\s+/g," ").trim();if(!name||name.length<2||/^(company|name|view all)$/i.test(name))continue;const id=idFor(name);if(seen.has(id))continue;seen.add(id);const after=row.slice(row.indexOf(dates[1])+dates[1].length);const price=parsePriceBand(after);const xs=[...after.matchAll(/(\d+(?:\.\d+)?)\s*x\b/gi)].map(m=>num(m[1])).filter((v):v is number=>v!=null);out.push({id,name,type,closeDate:parseDate(dates[1]),minSubscription:null,subscription:xs.length?xs[0]:null,subscriptionSource:xs.length?"Groww verified":null,gmpPct:null,gmpSources:[],city:null,state:null,business:null,countries:[],profits:[],priceBand:price,lotSize:null,verifiedAt:new Date().toISOString()})}return out}
function parseUpcoming(html:string){const rows=[...html.matchAll(/<tr\b[\s\S]*?<\/tr>/gi)].map(m=>clean(m[0])).filter(Boolean);const out:Ipo[]=[];for(const row of rows){const dates=[...row.matchAll(/\d{1,2}\s*(?:-|to)\s*\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}|\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}/g)].map(m=>m[0]);const dateText=dates[0];if(!dateText)continue;const name=row.split(/\d{1,2}\s*(?:-|to)\s*\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}|\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}/)[0].replace(/Company Name|Issue Date|Price Range|Issue Size|Action|Image:/gi," ").replace(/\b(Mainboard|SME)\b/gi," ").replace(/IPO\s*$/i,"").replace(/\s+/g," ").trim();if(!name||name.length<2)continue;const parts=dateText.split(/\s*(?:-|to)\s*/);const close=parts.length>1?parseDate(`${parts[1]}`):parseDate(dateText);const price=parsePriceBand(row);const lotMatch=row.match(/(\d[\d,]*)\s*(?:shares|Shares)/i);out.push({id:idFor(name),name,type:/\bSME\b/i.test(row)?"SME":"Mainboard",closeDate:close,minSubscription:null,subscription:null,subscriptionSource:null,gmpPct:null,gmpSources:[],city:null,state:null,business:null,countries:[],profits:[],priceBand:price,lotSize:lotMatch?Number(lotMatch[1].replace(/,/g,"")):null,verifiedAt:new Date().toISOString()})}return out}
function parseSubscriptionTable(html:string){const map=new Map<string,number>();for(const row of [...html.matchAll(/<tr\b[\s\S]*?<\/tr>/gi)].map(m=>clean(m[0]))){const xs=[...row.matchAll(/(\d+(?:\.\d+)?)\s*x\b/gi)].map(m=>num(m[1])).filter((v):v is number=>v!=null);if(!xs.length)continue;const dates=[...row.matchAll(/\d{1,2}\s+[A-Za-z]{3,9}\s+\d{4}/g)];const prefix=dates.length?row.slice(0,dates[0].index):row;const name=prefix.replace(/Image:\s*/i,"").replace(/\b(Mainboard|SME)\b/gi," ").replace(/Company Name|Type/gi," ").replace(/\s+/g," ").trim();if(name)map.set(norm(name),xs[xs.length-1])}return map}
function parseAngelSubscription(html:string,name:string){const t=clean(html),idx=t.toLowerCase().indexOf(norm(name));const area=idx>=0?t.slice(idx,idx+5000):t;const m=area.match(/Subscription[\s\S]{0,1200}?(?:Total|Overall)[^\d]{0,80}(\d+(?:\.\d+)?)/i);return m?num(m[1]):null}
function parseAngelDetails(html:string,name:string){const t=clean(html),idx=t.toLowerCase().indexOf(norm(name));const area=idx>=0?t.slice(idx,idx+18000):t;const price=parsePriceBand(area);const lot=area.match(/(?:lot size|minimum investment)[^\d]{0,80}(\d[\d,]*)\s*(?:shares)?/i);const issue=area.match(/Issue Size[^₹\d]{0,30}₹?\s*([\d,.]+)\s*Cr/i);const businessMatch=area.match(/About\s+(?:the\s+)?[^\:]{0,80}[:]?\s*([\s\S]{0,900}?)(?:Industry Outlook|Financial Performance|IPO Objectives)/i);const dates=[...area.matchAll(/(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2},?\s+\d{2,4}/gi)].map(m=>m[0]);return {priceBand:price,lotSize:lot?Number(lot[1].replace(/,/g,"")):null,minSubscription:issue?Number(issue[1].replace(/,/g,"")):null,business:businessMatch?.[1]?.trim()??null,closeDate:dates.length?parseDate(dates[Math.min(1,dates.length-1)]):null}}
function fallbackDetails():Ipo[]{const now=new Date().toISOString();return[{id:"deepa-jewellers",name:"Deepa Jewellers",type:"Mainboard",closeDate:"2026-09-03",minSubscription:14868,subscription:null,subscriptionSource:null,gmpPct:null,gmpSources:[],city:"Hyderabad",state:"Telangana",business:"B2B designer, processor and supplier of hallmarked gold jewellery, mainly serving jewellery retail chains and standalone stores in India.",countries:[{country:"India",business:"Jewellery",salesPct:100}],profits:[{year:"FY24",value:24.35},{year:"FY25",value:40.58},{year:"FY26",value:104.79}],priceBand:"₹168 – ₹177",lotSize:84,verifiedAt:now},{id:"rays-of-belief",name:"Rays of Belief",type:"Mainboard",closeDate:"2026-09-03",minSubscription:14818,subscription:null,subscriptionSource:null,gmpPct:null,gmpSources:[],city:"New Delhi",state:"Delhi",business:"Healthcare social enterprise providing customised intervention and clinical care programs for children with neurodevelopmental disorders.",countries:[{country:"India",business:"Healthcare services",salesPct:null},{country:"United States",business:"Healthcare services",salesPct:null}],profits:[{year:"FY24",value:.85},{year:"FY25",value:5.88},{year:"FY26",value:4.96}],priceBand:"₹227 – ₹239",lotSize:62,verifiedAt:now},{id:"farm-peace",name:"Farm Peace",type:"SME",closeDate:"2026-09-03",minSubscription:118000,subscription:null,subscriptionSource:null,gmpPct:null,gmpSources:[],city:null,state:null,business:"Agriculture and farm-related products and services.",countries:[],profits:[],priceBand:"₹59",lotSize:2000,verifiedAt:now},{id:"fly-hi-maritime",name:"Fly-Hi Maritime",type:"SME",closeDate:"2026-09-03",minSubscription:null,subscription:null,subscriptionSource:null,gmpPct:null,gmpSources:[],city:null,state:null,business:"Maritime travel and related transportation services.",countries:[],profits:[],priceBand:"₹102",lotSize:1200,verifiedAt:now}];}
function todayIST(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}
async function enrichGmp(ipo:Ipo){const entries=Object.entries(GMP_SOURCE_URLS(ipo.id));const values:{source:string;pct:number|null}[]=[];for(const [source,url] of entries){try{const html=await getHtml(url,10000);const g=extractGmp(html);if(g!=null)values.push({source,pct:g})}catch{}}ipo.gmpSources=values;const valid=values.map(x=>x.pct).filter((x):x is number=>x!=null);ipo.gmpPct=valid.length>=2?median(valid):null}
async function loadIpos(){const hit=cache.get("open");if(hit&&hit.exp>Date.now())return hit.value;const [dashboard,subscription,angelUpcoming]=await Promise.allSettled([getHtml(GROWw_DASHBOARD),getHtml(GROWW_SUBSCRIPTION),getHtml(ANGEL_UPCOMING)]);let ipos=dashboard.status==="fulfilled"?parseDashboardOpen(dashboard.value):[];if(angelUpcoming.status==="fulfilled"){for(const x of parseUpcoming(angelUpcoming.value)){if(!ipos.some(y=>norm(y.name)===norm(x.name)))ipos.push(x)}}const today=todayIST();ipos=ipos.filter(x=>x.closeDate==null||x.closeDate>=today);if(!ipos.length)ipos=fallbackDetails().filter(x=>x.closeDate==null||x.closeDate>=today);const growwSubs=subscription.status==="fulfilled"?parseSubscriptionTable(subscription.value):new Map<string,number>();const enriched=await Promise.all(ipos.map(async ipo=>{try{const angelUrl=`https://www.angelone.in/ipo/${ipo.id}-ipo`;const angel=await getHtml(angelUrl,12000);const detail=parseAngelDetails(angel,ipo.name);if(detail.priceBand)ipo.priceBand=detail.priceBand;if(detail.lotSize)ipo.lotSize=detail.lotSize;if(detail.minSubscription)ipo.minSubscription=detail.minSubscription;if(detail.business)ipo.business=detail.business;if(detail.closeDate)ipo.closeDate=detail.closeDate;const angelSub=parseAngelSubscription(angel,ipo.name);const growwSub=growwSubs.get(norm(ipo.name))??null;const subs=[growwSub,angelSub].filter((x):x is number=>x!=null);ipo.subscription=subs.length?median(subs):null;ipo.subscriptionSource=growwSub!=null&&angelSub!=null?"Groww + Angel One verified":growwSub!=null?"Groww verified":angelSub!=null?"Angel One verified":null;}catch{const g=growwSubs.get(norm(ipo.name));ipo.subscription=g??ipo.subscription;ipo.subscriptionSource=g!=null?"Groww verified":null}await enrichGmp(ipo);ipo.verifiedAt=new Date().toISOString();return ipo;}catch{return ipo;}}));const byCompany=new Map<string,Ipo>();for(const q of enriched){const key=norm(q.name);if(!byCompany.has(key))byCompany.set(key,q)}cache.set("open",{exp:Date.now()+30_000,value:[...byCompany.values()]});return [...byCompany.values()]}
export const fetchOpenIpos=createServerFn({method:"POST"}).validator((data:unknown)=>z.object({refresh:z.boolean().optional()}).parse(data)).handler(async()=>{try{return await loadIpos()}catch{return fallbackDetails().filter(x=>x.closeDate==null||x.closeDate>=todayIST()).map(x=>({...x,subscription:null,subscriptionSource:null}))}});