import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { CHART_PERIODS, INDICES, MOVERS_UNIVERSE, PERIOD_MAP, displaySymbol, normalizeSymbol, type ChartPeriod } from "./config";
import type { Bar, Dividend, Quote, SearchHit } from "./types";

const UA = "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/122 Safari/537.36";
type CacheEntry = { exp: number; val: unknown };
type YahooMeta = { currency?: string; symbol?: string; exchangeName?: string; fullExchangeName?: string; regularMarketPrice?: number; regularMarketChangePercent?: number; fiftyTwoWeekHigh?: number; fiftyTwoWeekLow?: number; regularMarketDayHigh?: number; regularMarketDayLow?: number; regularMarketVolume?: number; longName?: string; shortName?: string; chartPreviousClose?: number; previousClose?: number };
const cache = new Map<string, CacheEntry>();
function record(v: unknown): Record<string, unknown> | null { return v && typeof v === "object" ? v as Record<string, unknown> : null; }
function number(v: unknown): number | null { if (typeof v === "number" && Number.isFinite(v)) return v; if (typeof v === "string" && v.trim()) { const n = Number(v); return Number.isFinite(n) ? n : null; } return null; }
function string(v: unknown): string | null { return typeof v === "string" && v.trim() ? v : null; }
async function getJson(url: string, headers?: HeadersInit): Promise<unknown> { const res = await fetch(url, { headers: { "User-Agent": UA, Accept: "application/json,text/plain,*/*", ...headers }, cache: "no-store" }); if (!res.ok) throw new Error(`HTTP ${res.status}`); return res.json(); }
async function cached<T>(key: string, ttl: number, fn: () => Promise<T>): Promise<T> { const hit = cache.get(key); if (hit && hit.exp > Date.now()) return hit.val as T; const value = await fn(); cache.set(key, { exp: Date.now() + ttl, val: value }); return value; }
function emptyQuote(symbol: string): Quote { return { symbol, name: displaySymbol(symbol), price: null, previousClose: null, change: null, changePct: null, currency: "INR", exchange: null, high52w: null, low52w: null, volume: null, dayHigh: null, dayLow: null, ok: false }; }
function makeQuote(meta: YahooMeta, fallback: string): Quote { const price = number(meta.regularMarketPrice); const previous = number(meta.chartPreviousClose) ?? number(meta.previousClose); const change = price != null && previous != null ? Math.round((price - previous) * 100) / 100 : null; const changePct = number(meta.regularMarketChangePercent) ?? (change != null && previous ? Math.round(change / previous * 10000) / 100 : null); return { symbol: string(meta.symbol) ?? fallback, name: string(meta.longName) ?? string(meta.shortName) ?? fallback, price, previousClose: previous, change, changePct, currency: string(meta.currency) ?? "INR", exchange: string(meta.fullExchangeName) ?? string(meta.exchangeName), high52w: number(meta.fiftyTwoWeekHigh), low52w: number(meta.fiftyTwoWeekLow), volume: number(meta.regularMarketVolume), dayHigh: number(meta.regularMarketDayHigh), dayLow: number(meta.regularMarketDayLow), ok: price != null }; }
function parseYahoo(raw: unknown): { bars: Bar[]; meta: YahooMeta; dividends: Dividend[] } { const chart = record(record(raw)?.chart); const result = record((Array.isArray(chart?.result) ? chart.result : [])[0]); if (!result) return { bars: [], meta: {}, dividends: [] }; const meta = (record(result.meta) ?? {}) as YahooMeta; const timestamps = Array.isArray(result.timestamp) ? result.timestamp : []; const indicators = record(result.indicators); const quote = record((Array.isArray(indicators?.quote) ? indicators.quote : [])[0]); const opens = Array.isArray(quote?.open) ? quote.open : []; const highs = Array.isArray(quote?.high) ? quote.high : []; const lows = Array.isArray(quote?.low) ? quote.low : []; const closes = Array.isArray(quote?.close) ? quote.close : []; const volumes = Array.isArray(quote?.volume) ? quote.volume : []; const bars: Bar[] = []; for (let i = 0; i < timestamps.length; i++) { const t = number(timestamps[i]), o = number(opens[i]), h = number(highs[i]), l = number(lows[i]), c = number(closes[i]), v = number(volumes[i]) ?? 0; if (t != null && o != null && h != null && l != null && c != null) bars.push({ t, o, h, l, c, v }); } const dividends: Dividend[] = []; const divMap = record(record(result.events)?.dividends); if (divMap) for (const item of Object.values(divMap)) { const row = record(item), amount = number(row?.amount), date = number(row?.date); if (amount != null && date != null) dividends.push({ t: date, amount }); } dividends.sort((a, b) => b.t - a.t); return { bars, meta, dividends }; }
async function yahooChart(symbol: string, range: string, interval: string, events = false): Promise<unknown> { const params = new URLSearchParams({ range, interval, includePrePost: "false" }); if (events) params.set("events", "div"); return cached(`chart:${symbol}:${range}:${interval}:${events}`, 60_000, () => getJson(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?${params}`)); }
function quoteFromParsed(parsed: { bars: Bar[]; meta: YahooMeta }, symbol: string): Quote { const last = parsed.bars.at(-1); const prev = parsed.bars.length > 1 ? parsed.bars.at(-2) : undefined; const meta: YahooMeta = { ...parsed.meta, regularMarketPrice: number(parsed.meta.regularMarketPrice) ?? last?.c, chartPreviousClose: number(parsed.meta.chartPreviousClose) ?? number(parsed.meta.previousClose) ?? prev?.c }; return makeQuote(meta, symbol); }
async function yahooQuotes(symbols: string[]): Promise<Quote[]> { const unique = [...new Set(symbols.filter(Boolean).map(normalizeSymbol))]; return Promise.all(unique.map(async symbol => { try { let parsed = parseYahoo(await yahooChart(symbol, "1d", "1m")); if (!parsed.bars.length) parsed = parseYahoo(await yahooChart(symbol, "5d", "1d")); if (!parsed.bars.length) parsed = parseYahoo(await yahooChart(symbol, "1mo", "1d")); return quoteFromParsed(parsed, symbol); } catch { try { return quoteFromParsed(parseYahoo(await yahooChart(symbol, "5d", "1d")), symbol); } catch { return emptyQuote(symbol); } } })); }
function limitBars(bars: Bar[], period: ChartPeriod): Bar[] { if (period !== "3Y") return bars; const cutoff = Date.now() / 1000 - 3 * 365 * 24 * 60 * 60; return bars.filter(b => b.t >= cutoff); }
export const fetchDashboard = createServerFn({ method: "POST" }).handler(async () => { const [indexQuotes, moverQuotes] = await Promise.all([yahooQuotes(INDICES.map(i => i.symbol)), yahooQuotes([...MOVERS_UNIVERSE])]); const bySym = new Map(indexQuotes.map(q => [q.symbol, q])); const indices = INDICES.map(i => ({ name: i.name, short: i.short, quote: bySym.get(i.symbol) ?? emptyQuote(i.symbol) })); const movers = moverQuotes.filter(q => q.ok && q.changePct != null).sort((a, b) => (b.changePct ?? 0) - (a.changePct ?? 0)); return { indices, gainers: movers.slice(0, 5), losers: [...movers].reverse().slice(0, 5) }; });
export const fetchQuotes = createServerFn({ method: "POST" }).validator((data: unknown) => z.object({ symbols: z.array(z.string()).max(40) }).parse(data)).handler(async ({ data }) => yahooQuotes(data.symbols));
export const fetchHistory = createServerFn({ method: "POST" }).validator((data: unknown) => z.object({ symbol: z.string().min(1).max(24), period: z.enum(CHART_PERIODS).default("1Y") }).parse(data)).handler(async ({ data }) => { const symbol = normalizeSymbol(data.symbol), spec = PERIOD_MAP[data.period]; const parsed = parseYahoo(await yahooChart(symbol, spec.range, spec.interval)); return { symbol, bars: limitBars(parsed.bars, data.period), quote: quoteFromParsed(parsed, symbol) }; });
export const fetchAnalysis = createServerFn({ method: "POST" }).validator((data: unknown) => z.object({ symbol: z.string().min(1).max(24), period: z.enum(CHART_PERIODS).default("1Y") }).parse(data)).handler(async ({ data }) => { const symbol = normalizeSymbol(data.symbol), spec = PERIOD_MAP[data.period]; const [fiveRaw, periodRaw] = await Promise.all([yahooChart(symbol, "5y", "1d", true), data.period === "1D" || data.period === "1W" ? yahooChart(symbol, spec.range, spec.interval) : Promise.resolve(null)]); const five = parseYahoo(fiveRaw); const period = periodRaw ? parseYahoo(periodRaw) : five; const quote = quoteFromParsed(five, symbol).ok ? quoteFromParsed(five, symbol) : quoteFromParsed(period, symbol); const yearAgo = Date.now() / 1000 - 365 * 24 * 60 * 60; const bars1y = five.bars.filter(b => b.t >= yearAgo); return { symbol, quote, bars: limitBars(period.bars, data.period), bars1y: bars1y.length ? bars1y : five.bars.slice(-260), bars5y: five.bars, dividends: five.dividends, company: null, fundamentals: [], statements: [] }; });
export const fetchWatchPack = createServerFn({ method: "POST" }).validator((data: unknown) => z.object({ symbols: z.array(z.string()).max(20) }).parse(data)).handler(async ({ data }) => { const symbols = data.symbols.map(normalizeSymbol); const quotes = await yahooQuotes(symbols); const packs = await Promise.all(symbols.map(async symbol => { try { const [one, five] = await Promise.all([yahooChart(symbol, "1y", "1d"), yahooChart(symbol, "5y", "1wk")]); return { symbol, bars1y: parseYahoo(one).bars, bars5y: parseYahoo(five).bars }; } catch { return { symbol, bars1y: [] as Bar[], bars5y: [] as Bar[] }; } })); return { quotes, packs }; });
export const searchSymbols = createServerFn({ method: "POST" }).validator((data: unknown) => z.object({ q: z.string().min(1).max(40) }).parse(data)).handler(async ({ data }): Promise<SearchHit[]> => { const query = data.q.trim(); try { const raw = await getJson(`https://query1.finance.yahoo.com/v1/finance/search?q=${encodeURIComponent(query)}&quotesCount=10&newsCount=0`); const root = record(raw), quotes = Array.isArray(root?.quotes) ? root.quotes : [], hits: SearchHit[] = []; for (const item of quotes) { const row = record(item), symbol = string(row?.symbol); if (!symbol) continue; const type = string(row?.quoteType), exchange = string(row?.exchDisp) ?? ""; const indian = symbol.endsWith(".NS") || symbol.endsWith(".BO") || /NSE|BSE|Bombay/i.test(exchange); if (type && type !== "EQUITY" && type !== "INDEX") continue; if (!indian && !symbol.startsWith("^")) continue; hits.push({ symbol, name: string(row?.longname) ?? string(row?.shortname) ?? symbol, exchange: exchange || (symbol.endsWith(".BO") ? "BSE" : "NSE") }); } if (hits.length) return hits; } catch {} const normalized = normalizeSymbol(query); return [{ symbol: normalized, name: normalized, exchange: "NSE" }]; });