import { createServerFn } from "@tanstack/react-start";
import type { Quote } from "./types";

const UA = "Mozilla/5.0";
const cache = { exp: 0, symbols: [] as string[], data: [] as Quote[] };
const BSE_GROUPS = ["A", "B", "E", "F", "FC", "GC", "I", "IF", "IP", "M", "MS", "MT", "P", "R", "T", "TS", "W", "X", "XD", "XT", "Y", "Z", "ZP", "ZY"];
type Chart = { chart?: { result?: Array<{ meta?: Record<string, unknown>; timestamp?: number[]; indicators?: { quote?: Array<{ high?: Array<number | null>; close?: Array<number | null> }> } }> } };
type Period = "current" | "1d" | "1w" | "1m" | "3m" | "6m";
type Suggestion = Quote & { triggerDates: string[]; sector: string | null };
function num(v: unknown) { return typeof v === "number" && Number.isFinite(v) ? v : null; }
function indiaDate(ts: number) { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kolkata", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(ts * 1000)); }
async function nseUniverse(): Promise<string[]> { try { const res = await fetch("https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv", { headers: { "User-Agent": UA, Accept: "text/csv,*/*" }, cache: "no-store" }); if (!res.ok) return []; const lines = (await res.text()).split(/\r?\n/).filter(Boolean); const h = lines.shift()?.split(",").map(x => x.trim().replace(/^\"|\"$/g, "").toUpperCase()) ?? []; const si = h.indexOf("SYMBOL"), se = h.indexOf("SERIES"); if (si < 0) return []; return lines.map(x => x.split(",").map(v => v.trim().replace(/^\"|\"$/g, ""))).filter(c => se < 0 || c[se] === "EQ").map(c => c[si]).filter(Boolean).map(s => `${s}.NS`); } catch { return []; } }
async function bseUniverse(): Promise<string[]> { const out = new Set<string>(); for (const group of BSE_GROUPS) { try { const u = new URL("https://api.bseindia.com/BseIndiaAPI/api/ListofScripData/w"); u.searchParams.set("scripcode", ""); u.searchParams.set("Group", group); u.searchParams.set("industry", ""); u.searchParams.set("segment", "Equity"); u.searchParams.set("status", "Active"); const res = await fetch(u, { headers: { "User-Agent": UA, Accept: "application/json, text/plain, */*", Referer: "https://www.bseindia.com/" }, cache: "no-store" }); if (!res.ok) continue; const raw = await res.json() as unknown; const rows = Array.isArray(raw) ? raw : raw && typeof raw === "object" && Array.isArray((raw as { Data?: unknown }).Data) ? (raw as { Data: unknown[] }).Data : []; for (const item of rows) { if (!item || typeof item !== "object") continue; const r = item as Record<string, unknown>; const code = String(r.scripcode ?? r.SCRIPCODE ?? r.scripCode ?? "").trim(); if (/^\d{6}$/.test(code)) out.add(`${code}.BO`); } } catch {} } return [...out]; }
async function universe(): Promise<string[]> { if (cache.symbols.length) return cache.symbols; const [nse, bse] = await Promise.all([nseUniverse(), bseUniverse()]); const all = [...new Set([...nse, ...bse])]; if (all.length) cache.symbols = all; return cache.symbols; }
async function history(symbol: string) { for (const host of ["query1.finance.yahoo.com", "query2.finance.yahoo.com"]) { try { const u = new URL(`https://${host}/v8/finance/chart/${encodeURIComponent(symbol)}`); u.searchParams.set("range", "5y"); u.searchParams.set("interval", "1d"); const res = await fetch(u, { headers: { "User-Agent": UA, Accept: "application/json" }, cache: "no-store" }); if (!res.ok) continue; const raw = await res.json() as Chart; const row = raw.chart?.result?.[0]; const highs = row?.indicators?.quote?.[0]?.high ?? []; const closes = row?.indicators?.quote?.[0]?.close ?? []; const timestamps = row?.timestamp ?? []; const validHighs = highs.map(num).filter((x): x is number => x !== null); const price = num(row?.meta?.regularMarketPrice) ?? [...closes].reverse().map(num).find((x): x is number => x !== null) ?? null; if (price === null || !validHighs.length) continue; const high5y = Math.max(...validHighs); const thresholdFor = (p:number) => p < 20 ? high5y * 0.10 : high5y * 0.25; const threshold = thresholdFor(price); const triggerDates:string[]=[]; for (let i=1;i<closes.length;i++){const prev=num(closes[i-1]),cur=num(closes[i]); if(prev!==null&&cur!==null&&timestamps[i]!=null){const thresholdOnDay=thresholdFor(cur); if(prev>thresholdOnDay&&cur<=thresholdOnDay) triggerDates.push(indiaDate(timestamps[i]));}} return {price,high5y,threshold,triggerDates}; } catch {} } return null; }
async function sectorFor(symbol:string):Promise<string|null>{ for (const host of ["query1.finance.yahoo.com", "query2.finance.yahoo.com"]) { try { const u=new URL(`https://${host}/v10/finance/quoteSummary/${encodeURIComponent(symbol)}`);u.searchParams.set("modules","assetProfile");const res=await fetch(u,{headers:{"User-Agent":UA,Accept:"application/json"},cache:"no-store"});if(!res.ok)continue;const raw=await res.json() as {quoteSummary?:{result?:Array<{assetProfile?:{sector?:string;industry?:string}}>}};const p=raw.quoteSummary?.result?.[0]?.assetProfile;if(!p)continue;const value=[p.sector,p.industry].filter(Boolean).join(" | ");if(value)return value;}catch{} } return null; }
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T)=>Promise<R>):Promise<R[]>{const out:R[] = new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;try{out[i]=await fn(items[i]);}catch{out[i]=undefined as R;}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>worker()));return out;}
function periodStart(period:Period){const d=new Date();if(period==="1d")d.setDate(d.getDate()-1);if(period==="1w")d.setDate(d.getDate()-7);if(period==="1m")d.setMonth(d.getMonth()-1);if(period==="3m")d.setMonth(d.getMonth()-3);if(period==="6m")d.setMonth(d.getMonth()-6);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}
function sectorMatches(value:string|null, selected:string){if(selected==="All")return true;if(!value)return false;const v=value.toLowerCase();const aliases:Record<string,string[]|undefined>={"IT":["information technology","technology","software","semiconductors","it services"],"FMCG":["consumer defensive","consumer staples","packaged foods","household products","personal products","beverages","food products"],"Medicine":["healthcare","health care","pharmaceutical","biotechnology","medical","drug manufacturers"],"Banking":["banks","bank"],"Finance":["financial services","credit services","capital markets","insurance","mortgage finance"],"Automobile":["auto manufacturers","automobiles","auto parts","vehicles"],"Chemicals":["chemicals","specialty chemicals"],"Real Estate":["real estate","reit"],"Energy":["energy","oil & gas","utilities"],"Industrials":["industrials","industrial products","aerospace & defense","engineering"],"Utilities":["utilities","electric utilities","gas utilities"],"Communication Services":["communication services","telecom","internet content & information"]};return (aliases[selected]??[selected.toLowerCase()]).some(a=>v.includes(a));}
async function getSuggestions(period:Period="current",sector="All"):Promise<Quote[]>{try{const symbols=await universe();if(!symbols.length)return cache.data;const rows=await mapLimit(symbols,32,async symbol=>({symbol,data:await history(symbol)}));const candidates=rows.filter((r):r is {symbol:string;data:NonNullable<Awaited<ReturnType<typeof history>>>}=>!!r?.data&&(period==="current"?r.data.price<=r.data.threshold:r.data.triggerDates.some(d=>d>=periodStart(period))));
// IMPORTANT: enrich every qualifying candidate before applying the selected sector filter.
// Limiting enrichment to the first 12 candidates made most sector selections incorrectly return 0 stocks.
const enriched=await mapLimit(candidates,24,async r=>({...r,sector:await sectorFor(r.symbol)}));
const result:Suggestion[]=enriched.map(({symbol,data,sector})=>({symbol,name:symbol.replace(/\.NS$|\.BO$/i,""),price:data.price,previousClose:null,change:null,changePct:null,currency:"INR",exchange:symbol.endsWith(".BO")?"BSE":"NSE",high52w:null,low52w:null,high5y:data.high5y,low5y:null,price75:Math.round(data.threshold*100)/100,signal75:data.price<=data.threshold?"BUY":"WAIT",volume:null,dayHigh:null,dayLow:null,ok:true,triggerDate:data.triggerDates.at(-1)??null,triggerDates:data.triggerDates,sector:sector??null}));const byCompany=new Map<string,Suggestion>();for(const q of result){const key=q.name.replace(/[^A-Z0-9]/gi,"").toUpperCase();const old=byCompany.get(key);if(!old||(q.exchange==="NSE"&&old.exchange==="BSE"))byCompany.set(key,q);}let all=[...byCompany.values()];if(sector!=="All")all=all.filter(q=>sectorMatches(q.sector,sector));if(period==="current"){const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());const todayRows=all.filter(q=>q.triggerDate===today).sort((a,b)=>a.name.localeCompare(b.name));const other=all.filter(q=>q.triggerDate!==today).sort((a,b)=>a.name.localeCompare(b.name));cache.data=[...todayRows,...other];}else{const start=periodStart(period);cache.data=all.map(q=>({...q,triggerDate:[...q.triggerDates].filter(d=>d>=start).sort().at(-1)??null})).sort((a,b)=>(b.triggerDate??"").localeCompare(a.triggerDate??""));}cache.exp=Date.now()+300000;return cache.data;}catch{return cache.data;}}
export const fetchSuggestions=createServerFn({method:"POST"}).handler(async({data}:{data?:{period?:Period;sector?:string}})=>getSuggestions(data?.period??"current",data?.sector??"All"));
