import { createServerFn } from "@tanstack/react-start";
import type { Quote } from "./types";

type Chart = { chart?: { result?: Array<{ meta?: Record<string, unknown>; timestamp?: number[]; indicators?: { quote?: Array<{ high?: Array<number | null>; close?: Array<number | null> }> } }> } };
const UA="Mozilla/5.0";
const RESULT_TTL=10*60_000;
const UNIVERSE_TTL=24*60*60_000;
const cache={exp:0,symbols:[] as string[],sectors:new Map<string,string>(),results:new Map<string,{exp:number;data:Quote[]}>,history:new Map<string,{exp:number;data:Awaited<ReturnType<typeof history>>>}>;
type Period="current"|"1d"|"1w"|"1m"|"3m"|"6m";
type Suggestion=Quote&{triggerDates:string[];sector:string|null};
type FastQuote={symbol:string;price:number;previousClose:number|null;high52w:number|null};
function num(v:unknown){return typeof v==="number"&&Number.isFinite(v)?v:null;}
function indiaDate(ts:number){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(ts*1000));}
function indiaToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function clean(s:string){return s.trim().replace(/^\"|\"$/g,"");}
function classifyText(value:string){const v=value.toLowerCase();if(["healthcare","pharma","pharmaceutical","biotechnology","medical","drug","diagnostic"].some(x=>v.includes(x)))return"Medicine / Pharma";if(["information technology","technology","software","semiconductor","it services"].some(x=>v.includes(x)))return"IT";if(["consumer defensive","consumer staples","packaged food","household","personal product","beverage","food product","tobacco"].some(x=>v.includes(x)))return"FMCG";if(v.includes("bank"))return"Banking";if(["financial services","credit services","capital markets","insurance","mortgage","asset management"].some(x=>v.includes(x)))return"Finance";if(["auto manufacturer","automobile","auto parts","vehicle"].some(x=>v.includes(x)))return"Automobile";if(["chemical","specialty chemical"].some(x=>v.includes(x)))return"Chemicals";if(["real estate","reit","property development"].some(x=>v.includes(x)))return"Real Estate";if(["oil & gas","oil gas","energy","petroleum"].some(x=>v.includes(x)))return"Energy";if(["utilities","electric utilities","gas utilities"].some(x=>v.includes(x)))return"Utilities";if(["communication services","telecom","internet content"].some(x=>v.includes(x)))return"Communication Services";if(["industrials","industrial product","aerospace","engineering","construction","machinery","infrastructure"].some(x=>v.includes(x)))return"Industrials";return null;}
async function nseUniverse():Promise<string[]>{try{const res=await fetch("https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv",{headers:{"User-Agent":UA,Accept:"text/csv,*/*"},cache:"no-store"});if(!res.ok)return[];const lines=(await res.text()).split(/\r?\n/).filter(Boolean);const h=lines.shift()?.split(",").map(clean).map(x=>x.toUpperCase())??[];const si=h.indexOf("SYMBOL"),se=h.indexOf("SERIES");if(si<0)return[];return lines.map(x=>x.split(",").map(clean)).filter(c=>se<0||c[se]==="EQ").map(c=>c[si]).filter(Boolean).map(s=>`${s}.NS`);}catch{return[];}}
async function universe(){if(cache.symbols.length&&Date.now()<cache.exp)return cache.symbols;const nse=await nseUniverse();if(nse.length){cache.symbols=nse;cache.exp=Date.now()+UNIVERSE_TTL;}return cache.symbols;}
async function history(symbol:string){const hit=cache.history.get(symbol);if(hit&&Date.now()<hit.exp)return hit.data;for(const host of ["query1.finance.yahoo.com","query2.finance.yahoo.com"]){try{const u=new URL(`https://${host}/v8/finance/chart/${encodeURIComponent(symbol)}`);u.searchParams.set("range","5y");u.searchParams.set("interval","1d");const res=await fetch(u,{headers:{"User-Agent":UA,Accept:"application/json"},cache:"no-store"});if(!res.ok)continue;const raw=await res.json() as Chart,row=raw.chart?.result?.[0],highs=row?.indicators?.quote?.[0]?.high??[],closes=row?.indicators?.quote?.[0]?.close??[],timestamps=row?.timestamp??[];const validHighs=highs.map(num).filter((x):x is number=>x!==null);const price=num(row?.meta?.regularMarketPrice)??[...closes].reverse().map(num).find((x):x is number=>x!==null)??null;if(price===null||!validHighs.length)continue;const high5y=Math.max(...validHighs),thresholdFor=(p:number)=>p<20?high5y*.10:high5y*.25,triggerDates:string[]=[];for(let i=1;i<closes.length;i++){const prev=num(closes[i-1]),cur=num(closes[i]);if(prev!==null&&cur!==null&&timestamps[i]!=null&&prev>thresholdFor(prev)&&cur<=thresholdFor(cur))triggerDates.push(indiaDate(timestamps[i]));}const data={price,high5y,threshold:thresholdFor(price),triggerDates};cache.history.set(symbol,{exp:Date.now()+24*60*60_000,data});return data;}catch{}}return null;}
async function chartQuote(symbol:string):Promise<FastQuote|null>{for(const host of ["query1.finance.yahoo.com","query2.finance.yahoo.com"]){try{const u=new URL(`https://${host}/v8/finance/chart/${encodeURIComponent(symbol)}`);u.searchParams.set("range","5d");u.searchParams.set("interval","1d");const res=await fetch(u,{headers:{"User-Agent":UA,Accept:"application/json"},cache:"no-store"});if(!res.ok)continue;const raw=await res.json() as Chart,row=raw.chart?.result?.[0],closes=row?.indicators?.quote?.[0]?.close??[];const vals=closes.map(num).filter((x):x is number=>x!==null);const price=num(row?.meta?.regularMarketPrice)??vals.at(-1)??null;const previousClose=num(row?.meta?.previousClose)??(vals.length>1?vals.at(-2)??null:null);if(price!==null)return{symbol,price,previousClose,high52w:null};}catch{}}return null;}
async function fastQuotes(symbols:string[]):Promise<FastQuote[]>{const out:FastQuote[]=[];const chunks:Array<string[]>=[];for(let i=0;i<symbols.length;i+=100)chunks.push(symbols.slice(i,i+100));await Promise.all(chunks.map(async chunk=>{for(const host of ["query1.finance.yahoo.com","query2.finance.yahoo.com"]){try{const u=new URL(`https://${host}/v7/finance/quote`);u.searchParams.set("symbols",chunk.join(","));const res=await fetch(u,{headers:{"User-Agent":UA,Accept:"application/json"},cache:"no-store"});if(!res.ok)continue;const raw=await res.json() as{quoteResponse?:{result?:Array<Record<string,unknown>>}};for(const r of raw.quoteResponse?.result??[]){const symbol=String(r.symbol??""),price=num(r.regularMarketPrice),prev=num(r.regularMarketPreviousClose),high52=num(r.fiftyTwoWeekHigh);if(symbol&&price!==null)out.push({symbol,price,previousClose:prev,high52w:high52});}break;}catch{}}}));if(out.length>=Math.max(10,Math.floor(symbols.length*.15)))return out;const fallback=await mapLimit(symbols,48,chartQuote);return [...out,...fallback.filter((x):x is FastQuote=>!!x&&!out.some(y=>y.symbol===x.symbol))];}
async function yahooProfile(symbol:string){if(cache.sectors.has(symbol))return cache.sectors.get(symbol)??null;for(const host of ["query1.finance.yahoo.com","query2.finance.yahoo.com"]){try{const u=new URL(`https://${host}/v10/finance/quoteSummary/${encodeURIComponent(symbol)}`);u.searchParams.set("modules","assetProfile");const res=await fetch(u,{headers:{"User-Agent":UA,Accept:"application/json"},cache:"no-store"});if(!res.ok)continue;const raw=await res.json() as{quoteSummary?:{result?:Array<{assetProfile?:{sector?:string;industry?:string}}>} };const p=raw.quoteSummary?.result?.[0]?.assetProfile,mapped=p?classifyText(`${p?.sector??""} ${p?.industry??""}`):null;if(mapped){cache.sectors.set(symbol,mapped);return mapped;}}catch{}}return null;}
function exactSector(symbol:string){const s=symbol.replace(/\.(ns|bo)$/i,"").toUpperCase();const exact:Record<string,string>={RELIANCE:"Energy",ONGC:"Energy",IOC:"Energy",BPCL:"Energy",HINDPETRO:"Energy",TATAMOTORS:"Automobile",MARUTI:"Automobile",EICHERMOT:"Automobile","BAJAJ-AUTO":"Automobile",HEROMOTOCO:"Automobile",HDFCBANK:"Banking",ICICIBANK:"Banking",SBIN:"Banking",KOTAKBANK:"Banking",AXISBANK:"Banking",INDUSINDBK:"Banking",FEDERALBNK:"Banking",IDFCFIRSTB:"Banking",ITC:"FMCG",HINDUNILVR:"FMCG",NESTLEIND:"FMCG",BRITANNIA:"FMCG",DABUR:"FMCG",MARICO:"FMCG",COLPAL:"FMCG",TATACONSUM:"FMCG",SUNPHARMA:"Medicine / Pharma",DRREDDY:"Medicine / Pharma",CIPLA:"Medicine / Pharma",DIVISLAB:"Medicine / Pharma",AUROPHARMA:"Medicine / Pharma",LUPIN:"Medicine / Pharma",ZYDUSLIFE:"Medicine / Pharma",TORNTPHARM:"Medicine / Pharma",TECHM:"IT",TCS:"IT",INFY:"IT",WIPRO:"IT",HCLTECH:"IT",LTIM:"IT",MPHASIS:"IT",COFORGE:"IT",PERSISTENT:"IT"};return exact[s]??null;}
async function mapLimit<T,R>(items:T[],limit:number,fn:(item:T)=>Promise<R>):Promise<R[]>{const out:R[]=new Array(items.length);let next=0;async function worker(){while(true){const i=next++;if(i>=items.length)return;try{out[i]=await fn(items[i]);}catch{out[i]=undefined as R;}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>worker()));return out;}
function periodStart(period:Period){const d=new Date();if(period==="1d")d.setDate(d.getDate()-1);if(period==="1w")d.setDate(d.getDate()-7);if(period==="1m")d.setMonth(d.getMonth()-1);if(period==="3m")d.setMonth(d.getMonth()-3);if(period==="6m")d.setMonth(d.getMonth()-6);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}
function makeSuggestion(symbol:string,price:number,high5y:number,triggerDates:string[],previousClose:number|null):Suggestion{return{symbol,name:symbol.replace(/\.NS$|\.BO$/i,""),price,previousClose,change:previousClose!==null?price-previousClose:null,changePct:previousClose&&previousClose!==0?(price-previousClose)/previousClose*100:null,currency:"INR",exchange:symbol.endsWith(".BO")?"BSE":"NSE",high52w:null,low52w:null,high5y,low5y:null,price75:Math.round((price<20?high5y*.10:high5y*.25)*100)/100,signal75:price<20?price<=high5y*.10?"BUY":"WAIT":price<=high5y*.25?"BUY":"WAIT",volume:null,dayHigh:null,dayLow:null,ok:true,triggerDate:triggerDates.at(-1)??null,triggerDates,sector:exactSector(symbol)};}
async function currentSuggestions(symbols:string[]):Promise<Suggestion[]>{const quotes=await fastQuotes(symbols);const possible=quotes.filter(q=>q.high52w===null||q.price<20?q.high52w===null||q.price<=q.high52w*.10:q.price<=q.high52w*.25);const rows=await mapLimit(possible,96,async q=>({q,data:await history(q.symbol)}));const today=indiaToday(),result:Suggestion[]=[];for(const r of rows){if(!r?.data)continue;const q=r.q,d=r.data,threshold=d.threshold;const crossedToday=q.previousClose!==null&&q.previousClose>threshold&&q.price<=threshold;if(crossedToday&&!d.triggerDates.includes(today))d.triggerDates.push(today);if(q.price<=threshold||d.triggerDates.includes(today))result.push(makeSuggestion(q.symbol,q.price,d.high5y,d.triggerDates,q.previousClose));}return result;}
async function historicalSuggestions(symbols:string[],period:Period){const start=periodStart(period);const rows=await mapLimit(symbols,128,async symbol=>({symbol,data:await history(symbol)}));return rows.filter((r):r is {symbol:string;data:NonNullable<Awaited<ReturnType<typeof history>>>}=>!!r?.data&&r.data.triggerDates.some(d=>d>=start)).map(r=>makeSuggestion(r.symbol,r.data.price,r.data.high5y,r.data.triggerDates,null));}
async function getSuggestions(period:Period="current",sector="All"):Promise<Quote[]>{const key=`${period}:${sector}`,hit=cache.results.get(key);if(hit&&Date.now()<hit.exp)return hit.data;const symbols=await universe();if(!symbols.length)return[];let result:Suggestion[]=period==="current"?await currentSuggestions(symbols):await historicalSuggestions(symbols,period);if(sector!=="All"){const enriched=await mapLimit(result,24,async r=>({...r,sector:exactSector(r.symbol)??await yahooProfile(r.symbol)}));result=enriched.filter(r=>r.sector===sector);}const today=indiaToday(),byCompany=new Map<string,Suggestion>();for(const q of result){const k=q.name.replace(/[^A-Z0-9]/gi,"").toUpperCase(),old=byCompany.get(k);if(!old||(q.exchange==="NSE"&&old.exchange==="BSE"))byCompany.set(k,q);}const all=[...byCompany.values()];if(period==="current"){const todayRows=all.filter(q=>q.triggerDate===today).sort((a,b)=>a.name.localeCompare(b.name)),todaySet=new Set(todayRows.map(x=>x.symbol));result=[...todayRows,...all.filter(x=>!todaySet.has(x.symbol)).sort((a,b)=>a.name.localeCompare(b.name))];}else result=all.map(q=>({...q,triggerDate:[...q.triggerDates].filter(d=>d>=periodStart(period)).sort().at(-1)??null})).sort((a,b)=>(b.triggerDate??"").localeCompare(a.triggerDate??""));cache.results.set(key,{exp:Date.now()+RESULT_TTL,data:result});return result;}
export const fetchSuggestions=createServerFn({method:"POST"}).handler(async({data}:{data?:{period?:Period;sector?:string}})=>getSuggestions(data?.period??"current",data?.sector??"All"));