import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useRef, useState } from "react";
import { RefreshCw, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Empty, Panel, Section, Stat } from "@/components/widgets";
import { Signed } from "@/components/price";
import { displaySymbol } from "@/lib/market/config";
import { fmtCurrency } from "@/lib/market/math";
import { fetchQuotes } from "@/lib/market/server";
import { getAngelHoldings, getAngelStatus, getPortfolioTransactions, importPortfolioTransactions, syncAngelPortfolio } from "@/lib/market/angel-portfolio";

export const Route=createFileRoute("/portfolio")({component:PortfolioPage});
type Tx={id:string;broker:string;brokerTradeId:string|null;symbol:string;exchange:string;company:string;side:"BUY"|"SELL";quantity:number;price:number;tradeDate:string;charges:number;source:string};
type HoldingRow={symbol:string;exchange:string;qty:number;avg:number;invested:number;soldQty:number;boughtQty:number;realized:number};
type AngelHolding={symbol:string;exchange:string;company:string;quantity:number;averagePrice:number;lastPrice:number|null;pnl:number;updatedAt:string};

function PortfolioPage(){
 const qc=useQueryClient();const [tab,setTab]=useState<"holdings"|"sold"|"history">("holdings");const [syncing,setSyncing]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 const status=useQuery({queryKey:["angel-status"],queryFn:()=>getAngelStatus({data:undefined}),staleTime:60000});
 const txQuery=useQuery({queryKey:["portfolio-transactions"],queryFn:()=>getPortfolioTransactions({data:undefined}),refetchInterval:60000});
 const angelHoldingsQuery=useQuery({queryKey:["angel-holdings"],queryFn:()=>getAngelHoldings({data:undefined}),refetchInterval:60000});
 const transactions=(txQuery.data??[]) as Tx[];const angelHoldings=(angelHoldingsQuery.data??[]) as AngelHolding[];
 const symbols=[...new Set([...transactions.map(t=>t.symbol),...angelHoldings.map(h=>h.symbol)])];
 const quotes=useQuery({queryKey:["portfolio-quotes",symbols],queryFn:()=>fetchQuotes({data:{symbols}}),enabled:symbols.length>0,refetchInterval:60000});const quoteMap=new Map((quotes.data??[]).map(q=>[q.symbol,q]));
 const calculated=useMemo(()=>buildHoldings(transactions),[transactions]);
 const holdingRows=angelHoldings.length?angelHoldings.filter(h=>h.quantity>0.000001).map(h=>({symbol:h.symbol,exchange:h.exchange,qty:h.quantity,avg:h.averagePrice,invested:h.quantity*h.averagePrice,soldQty:0,boughtQty:h.quantity,realized:0})):calculated.filter(h=>h.qty>0.000001);
 const sold=transactions.filter(t=>t.side==="SELL");const totalInvested=holdingRows.reduce((s,h)=>s+h.invested,0);const currentValue=holdingRows.reduce((s,h)=>s+h.qty*(quoteMap.get(h.symbol)?.price??h.avg),0);const unrealized=currentValue-totalInvested;const realized=calculated.reduce((s,h)=>s+h.realized,0);const totalPl=unrealized+realized;const returnPct=totalInvested?(totalPl/totalInvested)*100:null;
 async function sync(){setSyncing(true);try{const result=await syncAngelPortfolio({data:undefined});toast(`Angel One synced · ${result.inserted} new trades`);await Promise.all([qc.invalidateQueries({queryKey:["portfolio-transactions"]}),qc.invalidateQueries({queryKey:["angel-holdings"]})]);}catch(err){toast(err instanceof Error?err.message:"Angel One sync failed");}finally{setSyncing(false);}}
 async function importCsv(file:File){const parsed=parseCsv(await file.text());if(!parsed.length){toast("No BUY/SELL rows found. Use Angel One trade-history CSV.");return;}try{const result=await importPortfolioTransactions({data:{transactions:parsed}});toast(`Imported ${result.inserted} historical trades`);await qc.invalidateQueries({queryKey:["portfolio-transactions"]});}catch(err){toast(err instanceof Error?err.message:"Import failed");}}
 return <div>
  <div className="flex items-start justify-between gap-3"><div><h1 className="font-display text-3xl tracking-tight">Portfolio</h1><p className="mt-1 text-sm text-muted">Holdings, sold shares and complete transaction history.</p></div><Button variant="secondary" size="sm" className="h-10" onClick={sync} disabled={syncing||!status.data?.configured} title={!status.data?.configured?"Configure Angel One server credentials first":"Sync Angel One"}><RefreshCw className={`mr-2 size-4 ${syncing?"animate-spin":""}`}/>Sync</Button></div>
  <div className="mt-4 grid grid-cols-2 gap-2"><Stat label="Invested" value={fmtCurrency(totalInvested)}/><Stat label="Current" value={fmtCurrency(currentValue)}/><Stat label="Total P/L" value={<Signed value={totalPl} as="currency" className="text-base"/>}/><Stat label="Return" value={<Signed value={returnPct} as="percent" className="text-base"/>}/></div>
  <div className="mt-4 grid grid-cols-3 gap-1 rounded-xl bg-surface-2 p-1">{([['holdings',`Holdings (${holdingRows.length})`],['sold',`Sold (${sold.length})`],['history',`History (${transactions.length})`]] as const).map(([value,label])=><button key={value} type="button" onClick={()=>setTab(value)} className={`rounded-lg px-2 py-2.5 text-xs font-medium ${tab===value?"bg-bg text-fg shadow-sm":"text-muted"}`}>{label}</button>)}</div>
  {tab==="holdings"?<Section title="Current Holdings" hint={angelHoldings.length?"Live holdings synced from Angel One":"Calculated from BUY minus SELL transactions"}>{holdingRows.length===0?<Empty title="No holdings yet" body="Connect Angel One or import your trade-history CSV."/>:<div className="space-y-2">{holdingRows.map(h=>{const current=quoteMap.get(h.symbol)?.price??h.avg;const value=h.qty*current;const pl=value-h.invested;return <Panel key={`${h.exchange}:${h.symbol}`} className="p-3"><div className="flex items-start justify-between gap-3"><Link to="/stock" search={{symbol:h.symbol,period:"1Y"}} className="min-w-0"><div className="font-medium">{displaySymbol(h.symbol)}</div><div className="text-xs text-muted">{h.exchange}</div></Link><Signed value={h.invested?(pl/h.invested)*100:null} as="percent"/></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-muted sm:grid-cols-4"><span>Qty <b className="tabular text-fg">{trim(h.qty)}</b></span><span>Avg <b className="tabular text-fg">{fmtCurrency(h.avg)}</b></span><span>Current <b className="tabular text-fg">{fmtCurrency(current)}</b></span><span>P/L <Signed value={pl} as="currency" className="text-xs"/></span></div></Panel>})}</div>}</Section>:null}
  {tab==="sold"?<Section title="Sold" hint="Actual SELL trades, newest first">{sold.length===0?<Empty title="No sold shares yet" body="Your Angel One SELL trades will appear here after sync."/>:<div className="space-y-2">{sold.map(t=><TransactionCard key={t.id} tx={t}/>)}</div>}</Section>:null}
  {tab==="history"?<Section title="Transaction History" hint="BUY + SELL, date-wise">{transactions.length===0?<Empty title="No transactions" body="Sync Angel One or import history."/>:<div className="space-y-2">{transactions.map(t=><TransactionCard key={t.id} tx={t}/>)}</div>}</Section>:null}
  <Panel className="mt-4 p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-medium">Angel One</div><div className="mt-1 text-xs text-muted">{status.data?.configured?"Read-only sync is ready.":"Add Angel One SmartAPI server secrets to enable sync."}</div></div><span className={`rounded-full px-2 py-1 text-[11px] ${status.data?.configured?"bg-up/15 text-up":"bg-surface-2 text-muted"}`}>{status.data?.configured?"Ready":"Not connected"}</span></div><input ref={fileRef} type="file" accept=".csv,text/csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importCsv(f);e.currentTarget.value=""}}/><Button variant="secondary" className="mt-3 w-full" onClick={()=>fileRef.current?.click()}><Upload className="mr-2 size-4"/>Import Angel One history CSV</Button></Panel>
  <p className="mt-3 text-center text-[11px] text-subtle">Artha does not place BUY/SELL orders. It only reads portfolio data and stores your transaction history.</p>
 </div>;
}
function TransactionCard({tx}:{tx:Tx}){return <Panel className="p-3"><div className="flex items-start justify-between gap-3"><div><div className="font-medium">{displaySymbol(tx.symbol)}</div><div className="text-xs text-muted">{tx.exchange} · {tx.tradeDate}</div></div><span className={`rounded-full px-2 py-1 text-[11px] font-medium ${tx.side==="BUY"?"bg-up/15 text-up":"bg-down/15 text-down"}`}>{tx.side}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs text-muted"><span>Qty <b className="tabular text-fg">{trim(tx.quantity)}</b></span><span>Price <b className="tabular text-fg">{fmtCurrency(tx.price)}</b></span><span>Value <b className="tabular text-fg">{fmtCurrency(tx.quantity*tx.price)}</b></span></div></Panel>}
function trim(n:number){return Number.isInteger(n)?String(n):n.toFixed(4).replace(/0+$/g,"").replace(/\.$/,"")}
function buildHoldings(txs:Tx[]):HoldingRow[]{const map=new Map<string,HoldingRow>();for(const t of [...txs].sort((a,b)=>a.tradeDate.localeCompare(b.tradeDate)||a.id.localeCompare(b.id))){const key=`${t.exchange}:${t.symbol}`;const row=map.get(key)??{symbol:t.symbol,exchange:t.exchange,qty:0,avg:0,invested:0,soldQty:0,boughtQty:0,realized:0};if(t.side==="BUY"){const newQty=row.qty+t.quantity;row.avg=newQty?(row.avg*row.qty+t.price*t.quantity)/newQty:t.price;row.qty=newQty;row.invested=row.qty*row.avg;row.boughtQty+=t.quantity;}else{const cost=row.avg*t.quantity;row.realized+=t.price*t.quantity-cost-t.charges;row.qty=Math.max(0,row.qty-t.quantity);row.invested=row.qty*row.avg;row.soldQty+=t.quantity;}map.set(key,row);}return [...map.values()].sort((a,b)=>a.symbol.localeCompare(b.symbol));}
function parseCsv(text:string):Tx[]{const lines=text.split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)return[];const parse=(line:string)=>line.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(x=>x.trim().replace(/^\"|\"$/g,""));const headers=parse(lines[0]).map(x=>x.toLowerCase().replace(/[^a-z0-9]/g,""));const find=(...names:string[])=>headers.findIndex(h=>names.includes(h));const dateI=find("tradedate","tradedatetime","date","transactiondate","orderdate");const symbolI=find("tradingsymbol","symbol","scrip","stock");const exchangeI=find("exchange","exchangename");const sideI=find("transactiontype","type","buysell","side");const qtyI=find("quantity","qty","filledquantity","fillshares","shares");const priceI=find("averageprice","price","tradeprice","fillprice","executedprice");if(dateI<0||symbolI<0||sideI<0||qtyI<0||priceI<0)return[];const out:Tx[]=[];for(let i=1;i<lines.length;i++){const c=parse(lines[i]);const rawSide=String(c[sideI]??"").toUpperCase();const side:Tx["side"]|null=rawSide.includes("BUY")?"BUY":rawSide.includes("SELL")?"SELL":null;const quantity=Number(String(c[qtyI]??"").replace(/,/g,""));const price=Number(String(c[priceI]??"").replace(/[₹,]/g,""));const symbol=String(c[symbolI]??"").trim();if(!side||!symbol||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(price))continue;const rawDate=String(c[dateI]??"").trim();const d=new Date(rawDate);const tradeDate=Number.isNaN(d.getTime())?rawDate.slice(0,10):d.toISOString().slice(0,10);const exchange=String(c[exchangeI]??"NSE").trim().toUpperCase()||"NSE";const id=`import-${i}-${symbol}-${tradeDate}-${side}-${quantity}-${price}`;out.push({id,broker:"manual-import",brokerTradeId:id,symbol:symbol.replace(/-EQ$/i,""),exchange,company:symbol,side,quantity,price,tradeDate,charges:0,source:"angel-csv"});}return out;}
