import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Empty, Panel } from "@/components/widgets";
import { Signed } from "@/components/price";
import { displaySymbol } from "@/lib/market/config";
import { fmtCurrency } from "@/lib/market/math";
import { fetchQuotes } from "@/lib/market/server";
import { addPortfolioAccount, addPortfolioTransaction, deletePortfolioTransaction, getPortfolioAccounts, getPortfolioTransactions, renamePortfolioAccount } from "@/lib/market/angel-portfolio";

export const Route=createFileRoute("/portfolio-angel-ui")({component:PortfolioPage});
type Account={id:string;name:string;sortOrder:number};
type Tx={id:string;broker:string;brokerTradeId:string|null;symbol:string;exchange:string;company:string;side:"BUY"|"SELL";quantity:number;price:number;tradeDate:string;charges:number;source:string};
type HoldingRow={symbol:string;exchange:string;qty:number;avg:number;invested:number;realized:number};
const txStorageKey=(accountId:string)=>`artha-portfolio-transactions-${accountId}`;
function readLocalTx(accountId:string):Tx[]{if(typeof window==="undefined"||!accountId)return [];try{const raw=localStorage.getItem(txStorageKey(accountId));const parsed=raw?JSON.parse(raw):[];return Array.isArray(parsed)?parsed:[]}catch{return [];}}
function writeLocalTx(accountId:string,transactions:Tx[]){if(typeof window==="undefined"||!accountId)return;try{localStorage.setItem(txStorageKey(accountId),JSON.stringify(transactions));}catch{}}

function PortfolioPage(){
 const qc=useQueryClient();
 const [accountId,setAccountId]=useState("");
 const [tab,setTab]=useState<"holdings"|"sold"|"history">("holdings");
 const [editing,setEditing]=useState<string|null>(null),[editName,setEditName]=useState("");
 const [showAdd,setShowAdd]=useState(false),[newAccount,setNewAccount]=useState("");
 const [showTx,setShowTx]=useState(false);
 const [tx,setTx]=useState({symbol:"",exchange:"NSE",side:"BUY" as "BUY"|"SELL",quantity:"",price:"",tradeDate:new Date().toISOString().slice(0,10),charges:"0"});
 const accountsQuery=useQuery({queryKey:["portfolio-accounts"],queryFn:()=>getPortfolioAccounts(),staleTime:300000});
 const accounts=(accountsQuery.data??[]) as Account[];
 useEffect(()=>{if(!accountId&&accounts[0]?.id)setAccountId(accounts[0].id)},[accounts,accountId]);
 const activeAccount=accounts.find(a=>a.id===accountId);
 const txQuery=useQuery({queryKey:["portfolio-transactions",accountId],queryFn:async()=>{const remote=await getPortfolioTransactions({data:{accountId}});const local=readLocalTx(accountId);const map=new Map<string,Tx>();for(const item of [...(local as Tx[]),...(remote as Tx[])])map.set(item.id,item);return [...map.values()].sort((a,b)=>`${b.tradeDate}-${b.id}`.localeCompare(`${a.tradeDate}-${a.id}`));},enabled:!!accountId,refetchInterval:60000});
 const transactions=(txQuery.data??[]) as Tx[];
 const symbols=[...new Set(transactions.map(t=>t.symbol))];
 const quotes=useQuery({queryKey:["portfolio-quotes",symbols],queryFn:()=>fetchQuotes({data:{symbols}}),enabled:symbols.length>0,refetchInterval:60000});
 const quoteMap=new Map((quotes.data??[]).map(q=>[q.symbol,q]));
 const calculated=useMemo(()=>buildHoldings(transactions),[transactions]);
 const holdingRows=calculated.filter(h=>h.qty>0.000001);
 const sold=transactions.filter(t=>t.side==="SELL");
 const totalInvested=holdingRows.reduce((s,h)=>s+h.invested,0);
 const currentValue=holdingRows.reduce((s,h)=>s+h.qty*(quoteMap.get(h.symbol)?.price??h.avg),0);
 const unrealized=currentValue-totalInvested;
 const realized=calculated.reduce((s,h)=>s+h.realized,0);
 const totalPl=unrealized+realized;
 const returnPct=totalInvested?(totalPl/totalInvested)*100:null;
 async function saveName(){if(!editing)return;try{await renamePortfolioAccount({data:{id:editing,name:editName}});toast("Account name updated");setEditing(null);await qc.invalidateQueries({queryKey:["portfolio-accounts"]})}catch(e){toast(e instanceof Error?e.message:"Could not update account")}}
 async function createAccount(){if(!newAccount.trim())return;try{const created=await addPortfolioAccount({data:{name:newAccount.trim()}});toast("Account added");setNewAccount("");setShowAdd(false);await qc.invalidateQueries({queryKey:["portfolio-accounts"]});setAccountId(created.id)}catch(e){toast(e instanceof Error?e.message:"Could not add account")}}
 async function saveTx(){const quantity=Number(tx.quantity),price=Number(tx.price),charges=Number(tx.charges||0);if(!accountId||!tx.symbol.trim()||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(price)||price<0||!/^\d{4}-\d{2}-\d{2}$/.test(tx.tradeDate)){toast("Enter valid transaction details");return}try{const result=await addPortfolioTransaction({data:{accountId,symbol:tx.symbol.trim(),exchange:tx.exchange,side:tx.side,quantity,price,tradeDate:tx.tradeDate,charges}});const localTx:Tx={id:String(result.id),broker:"manual",brokerTradeId:String(result.id),symbol:tx.symbol.trim().toUpperCase(),exchange:tx.exchange,company:tx.symbol.trim().toUpperCase(),side:tx.side,quantity,price,tradeDate:tx.tradeDate,charges:Number.isFinite(charges)&&charges>=0?charges:0,source:"manual"};writeLocalTx(accountId,[...readLocalTx(accountId).filter(item=>item.id!==localTx.id),localTx]);toast(`${tx.side} added and saved`);setShowTx(false);setTx({...tx,symbol:"",quantity:"",price:"",charges:"0"});await qc.invalidateQueries({queryKey:["portfolio-transactions",accountId]})}catch(e){toast(e instanceof Error?e.message:"Could not save transaction")}}
 async function removeTx(id:string){if(!confirm("Delete this transaction?"))return;try{await deletePortfolioTransaction({data:{accountId,id}});writeLocalTx(accountId,readLocalTx(accountId).filter(item=>item.id!==id));await qc.invalidateQueries({queryKey:["portfolio-transactions",accountId]});toast("Transaction deleted")}catch(e){toast(e instanceof Error?e.message:"Could not delete transaction")}}
 if(accountsQuery.isLoading)return <div className="py-12 text-center text-sm text-muted">Loading portfolio…</div>;
 return <div className="mx-auto max-w-6xl pb-10">
  <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-display text-3xl tracking-tight">Portfolio</h1><p className="mt-1 text-sm text-muted">Angel One-style portfolio view</p></div><Button className="h-10" onClick={()=>setShowTx(true)} disabled={!accountId}><Plus className="mr-2 size-4"/>Add Transaction</Button></div>
  <div className="mb-4 flex gap-2 overflow-x-auto border-b border-border pb-px">{accounts.map(a=><button key={a.id} onClick={()=>{setAccountId(a.id);setTab("holdings")}} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium ${accountId===a.id?"border-fg text-fg":"border-transparent text-muted hover:text-fg"}`}>{a.name}<span className="ml-2 text-[10px] text-muted">A{a.sortOrder}</span></button>)}<button onClick={()=>setShowAdd(true)} className="whitespace-nowrap px-4 py-3 text-sm text-muted hover:text-fg"><Plus className="mr-1 inline size-4"/>Add</button></div>
  {editing&&<div className="mb-4 flex gap-2 rounded-xl border border-border bg-surface-2 p-3"><input autoFocus value={editName} onChange={e=>setEditName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void saveName();if(e.key==="Escape")setEditing(null)}} className="min-w-0 flex-1 rounded-lg border bg-bg px-3 py-2 text-sm"/><Button size="sm" onClick={saveName}>Save</Button><Button size="sm" variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button></div>}
  {activeAccount&&<>
   <div className="rounded-2xl border border-border bg-bg p-5 shadow-sm">
    <div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex items-center gap-2"><h2 className="text-xl font-semibold">{activeAccount.name}</h2><button onClick={()=>{setEditing(activeAccount.id);setEditName(activeAccount.name)}} className="rounded p-1 text-muted hover:text-fg"><Pencil className="size-4"/></button></div><p className="mt-1 text-xs text-muted">Portfolio value</p><div className="mt-1 text-3xl font-semibold tabular">{fmtCurrency(currentValue)}</div></div><div className="min-w-[190px] text-right"><div className="text-xs text-muted">Overall P&amp;L</div><div className="mt-1 text-2xl font-semibold"><Signed value={totalPl} as="currency"/></div><div className="mt-1 text-sm"><Signed value={returnPct} as="percent"/></div></div></div>
    <div className="mt-6 grid grid-cols-2 gap-x-6 gap-y-4 border-t border-border pt-4 sm:grid-cols-4"><Metric label="Invested value" value={fmtCurrency(totalInvested)}/><Metric label="Current value" value={fmtCurrency(currentValue)}/><Metric label="Unrealised P&amp;L" value={<Signed value={unrealized} as="currency"/>}/><Metric label="Realised P&amp;L" value={<Signed value={realized} as="currency"/>}/></div>
   </div>
   <div className="mt-5 flex items-center justify-between border-b border-border"><div className="flex">{([['holdings',`Holdings ${holdingRows.length}`],['sold',`Sold ${sold.length}`],['history',`Orders ${transactions.length}`]] as const).map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`border-b-2 px-5 py-3 text-sm font-medium ${tab===v?"border-fg text-fg":"border-transparent text-muted hover:text-fg"}`}>{l}</button>)}</div></div>
   {tab==="holdings"&&<div className="mt-4 overflow-hidden rounded-2xl border border-border bg-bg"><div className="hidden grid-cols-7 border-b border-border bg-surface-2 px-4 py-3 text-[11px] font-medium uppercase tracking-wide text-muted md:grid"><span>Stock</span><span>Qty</span><span>Avg. price</span><span>LTP</span><span>Invested</span><span>Current value</span><span className="text-right">P&amp;L</span></div>{holdingRows.length===0?<div className="p-8"><Empty title="No holdings yet" body="Add a BUY transaction to build your portfolio."/></div>:holdingRows.map(h=>{const ltp=quoteMap.get(h.symbol)?.price??h.avg;const value=h.qty*ltp;const pl=value-h.invested;return <Link key={`${h.exchange}:${h.symbol}`} to="/stock" search={{symbol:h.symbol,period:"1Y"}} className="grid gap-3 border-b border-border px-4 py-4 last:border-b-0 hover:bg-surface-2/50 md:grid-cols-7 md:items-center"><div><div className="font-semibold">{displaySymbol(h.symbol)}</div><div className="text-xs text-muted">{h.exchange}</div></div><div className="text-sm"><span className="text-xs text-muted md:hidden">Qty · </span><b className="tabular">{trim(h.qty)}</b></div><div className="text-sm"><span className="text-xs text-muted md:hidden">Avg · </span><b className="tabular">{fmtCurrency(h.avg)}</b></div><div className="text-sm"><span className="text-xs text-muted md:hidden">LTP · </span><b className="tabular">{fmtCurrency(ltp)}</b></div><div className="text-sm"><span className="text-xs text-muted md:hidden">Invested · </span><b className="tabular">{fmtCurrency(h.invested)}</b></div><div className="text-sm"><span className="text-xs text-muted md:hidden">Value · </span><b className="tabular">{fmtCurrency(value)}</b></div><div className="text-right"><Signed value={pl} as="currency" className="text-sm"/><div className="text-xs"><Signed value={h.invested?(pl/h.invested)*100:null} as="percent"/></div></div></Link>})}</div>}
   {tab==="sold"&&<div className="mt-4 space-y-2">{sold.length===0?<Panel className="p-8"><Empty title="No sold shares" body="SELL transactions will appear here."/></Panel>:sold.map(t=><TransactionCard key={t.id} tx={t} onDelete={removeTx}/>)}</div>}
   {tab==="history"&&<div className="mt-4 space-y-2">{transactions.length===0?<Panel className="p-8"><Empty title="No orders yet" body="Your BUY and SELL activity will appear here."/></Panel>:transactions.map(t=><TransactionCard key={t.id} tx={t} onDelete={removeTx}/>)}</div>}
  </>}
  {showAdd&&<Modal title="Add Portfolio Account" close={()=>setShowAdd(false)}><input autoFocus value={newAccount} onChange={e=>setNewAccount(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void createAccount();if(e.key==="Escape")setShowAdd(false)}} className="w-full rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Account name"/><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setShowAdd(false)}>Cancel</Button><Button onClick={createAccount}>Add Account</Button></div></Modal>}
  {showTx&&<Modal title="Add Transaction" close={()=>setShowTx(false)}><div className="space-y-3"><input value={tx.symbol} onChange={e=>setTx({...tx,symbol:e.target.value.toUpperCase()})} className="w-full rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Stock symbol e.g. TCS"/><div className="grid grid-cols-2 gap-2"><select value={tx.side} onChange={e=>setTx({...tx,side:e.target.value as "BUY"|"SELL"})} className="rounded-lg border bg-bg px-3 py-2 text-sm"><option>BUY</option><option>SELL</option></select><select value={tx.exchange} onChange={e=>setTx({...tx,exchange:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm"><option>NSE</option><option>BSE</option></select></div><div className="grid grid-cols-2 gap-2"><input type="number" min="0.0001" value={tx.quantity} onChange={e=>setTx({...tx,quantity:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Quantity"/><input type="number" min="0" step="0.01" value={tx.price} onChange={e=>setTx({...tx,price:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Price"/></div><div className="grid grid-cols-2 gap-2"><input type="date" value={tx.tradeDate} onChange={e=>setTx({...tx,tradeDate:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm"/><input type="number" min="0" step="0.01" value={tx.charges} onChange={e=>setTx({...tx,charges:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Charges"/></div><Button className="w-full" onClick={saveTx}>Save Transaction</Button></div></Modal>}
 </div>;
}
function Metric({label,value}:{label:string;value:React.ReactNode}){return <div><div className="text-xs text-muted">{label}</div><div className="mt-1 text-sm font-semibold tabular">{value}</div></div>}
function TransactionCard({tx,onDelete}:{tx:Tx;onDelete:(id:string)=>void}){return <Panel className="p-4"><div className="flex items-center justify-between gap-3"><div><div className="font-semibold">{displaySymbol(tx.symbol)}</div><div className="text-xs text-muted">{tx.exchange} · {tx.tradeDate}</div></div><div className="flex items-center gap-3"><span className={`rounded px-2 py-1 text-xs font-semibold ${tx.side==="BUY"?"bg-up/15 text-up":"bg-down/15 text-down"}`}>{tx.side}</span><button onClick={()=>onDelete(tx.id)} className="text-muted hover:text-down"><Trash2 className="size-4"/></button></div></div><div className="mt-3 grid grid-cols-3 gap-3 border-t border-border pt-3 text-sm"><div><div className="text-xs text-muted">Qty</div><b className="tabular">{trim(tx.quantity)}</b></div><div><div className="text-xs text-muted">Price</div><b className="tabular">{fmtCurrency(tx.price)}</b></div><div><div className="text-xs text-muted">Value</div><b className="tabular">{fmtCurrency(tx.quantity*tx.price)}</b></div></div></Panel>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><Panel className="w-full max-w-md p-5"><div className="flex items-center justify-between"><h3 className="font-display text-xl">{title}</h3><button onClick={close} className="text-2xl leading-none text-muted">×</button></div><div className="mt-5">{children}</div></Panel></div>}
function trim(n:number){return Number.isInteger(n)?String(n):n.toFixed(4).replace(/0+$/g,"").replace(/\.$/,"")}
function buildHoldings(txs:Tx[]):HoldingRow[]{const map=new Map<string,HoldingRow>();for(const t of [...txs].sort((a,b)=>a.tradeDate.localeCompare(b.tradeDate)||a.id.localeCompare(b.id))){const key=`${t.exchange}:${t.symbol}`;const row=map.get(key)??{symbol:t.symbol,exchange:t.exchange,qty:0,avg:0,invested:0,realized:0};if(t.side==="BUY"){const newQty=row.qty+t.quantity;row.avg=newQty?(row.avg*row.qty+t.price*t.quantity)/newQty:t.price;row.qty=newQty;row.invested=row.qty*row.avg}else{const cost=row.avg*t.quantity;row.realized+=t.price*t.quantity-cost-t.charges;row.qty=Math.max(0,row.qty-t.quantity);row.invested=row.qty*row.avg}map.set(key,row)}return [...map.values()].sort((a,b)=>a.symbol.localeCompare(b.symbol))}
