import { useQuery,useQueryClient } from "@tanstack/react-query";
import { createFileRoute,Link } from "@tanstack/react-router";
import { useEffect,useMemo,useState,type ReactNode } from "react";
import { Pencil,Plus,Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Empty,Panel } from "@/components/widgets";
import { Signed } from "@/components/price";
import { displaySymbol } from "@/lib/market/config";
import { fmtCurrency } from "@/lib/market/math";
import { fetchQuotes } from "@/lib/market/server";
import { addPortfolioAccount,addPortfolioTransaction,deletePortfolioTransaction,getPortfolioAccounts,getPortfolioTransactions,renamePortfolioAccount } from "@/lib/market/angel-portfolio";

export const Route=createFileRoute("/portfolio")({component:PortfolioPage});
type Account={id:string;name:string;sortOrder:number};
type Tx={id:string;broker:string;brokerTradeId:string|null;symbol:string;exchange:string;company:string;side:"BUY"|"SELL";quantity:number;price:number;tradeDate:string;charges:number;source:string};
type Holding={symbol:string;exchange:string;qty:number;avg:number;invested:number;realized:number};
const key=(id:string)=>`artha-portfolio-transactions-${id}`;
const read=(id:string):Tx[]=>{if(typeof window==="undefined")return [];try{const x=JSON.parse(localStorage.getItem(key(id))||"[]");return Array.isArray(x)?x:[]}catch{return []}};
const write=(id:string,x:Tx[])=>{try{localStorage.setItem(key(id),JSON.stringify(x))}catch{}};

function PortfolioPage(){
 const qc=useQueryClient(),[accountId,setAccountId]=useState(""),[tab,setTab]=useState<"holdings"|"sold"|"history">("holdings"),[editing,setEditing]=useState<string|null>(null),[editName,setEditName]=useState(""),[showAdd,setShowAdd]=useState(false),[newAccount,setNewAccount]=useState(""),[showTx,setShowTx]=useState(false);
 const [tx,setTx]=useState({symbol:"",exchange:"NSE",side:"BUY" as "BUY"|"SELL",quantity:"",price:"",tradeDate:new Date().toISOString().slice(0,10),charges:"0"});
 const aq=useQuery({queryKey:["portfolio-accounts"],queryFn:()=>getPortfolioAccounts(),staleTime:300000}),accounts=(aq.data||[]) as Account[];
 useEffect(()=>{if(!accountId&&accounts[0])setAccountId(accounts[0].id)},[accounts,accountId]);
 const active=accounts.find(a=>a.id===accountId);
 const tq=useQuery({queryKey:["portfolio-transactions",accountId],enabled:!!accountId,refetchInterval:60000,queryFn:async()=>{const remote=await getPortfolioTransactions({data:{accountId}}),all=[...read(accountId),...(remote as Tx[])],m=new Map<string,Tx>();all.forEach(t=>m.set(t.id,t));return [...m.values()].sort((a,b)=>`${b.tradeDate}-${b.id}`.localeCompare(`${a.tradeDate}-${a.id}`))}}),transactions=(tq.data||[]) as Tx[];
 const symbols=[...new Set(transactions.map(t=>t.symbol))],quotes=useQuery({queryKey:["portfolio-quotes",symbols],enabled:symbols.length>0,refetchInterval:60000,queryFn:()=>fetchQuotes({data:{symbols}})}),qm=new Map((quotes.data||[]).map(q=>[q.symbol,q]));
 const holdings=useMemo(()=>build(transactions).filter(x=>x.qty>0.000001),[transactions]),sold=transactions.filter(t=>t.side==="SELL"),invested=holdings.reduce((s,x)=>s+x.invested,0),current=holdings.reduce((s,x)=>s+x.qty*(qm.get(x.symbol)?.price??x.avg),0),unreal=current-invested,realized=build(transactions).reduce((s,x)=>s+x.realized,0),pl=unreal+realized,ret=invested?pl/invested*100:null;
 async function rename(){if(!editing)return;try{await renamePortfolioAccount({data:{id:editing,name:editName}});setEditing(null);await qc.invalidateQueries({queryKey:["portfolio-accounts"]});toast("Account name updated")}catch(e){toast(e instanceof Error?e.message:"Could not update account")}}
 async function addAccount(){if(!newAccount.trim())return;try{const a=await addPortfolioAccount({data:{name:newAccount.trim()}});setNewAccount("");setShowAdd(false);await qc.invalidateQueries({queryKey:["portfolio-accounts"]});setAccountId(a.id);toast("Account added")}catch(e){toast(e instanceof Error?e.message:"Could not add account")}}
 async function saveTx(){const q=Number(tx.quantity),p=Number(tx.price),c=Number(tx.charges||0);if(!accountId||!tx.symbol.trim()||!Number.isFinite(q)||q<=0||!Number.isFinite(p)||p<0){toast("Enter valid transaction details");return}try{const r=await addPortfolioTransaction({data:{accountId,symbol:tx.symbol.trim(),exchange:tx.exchange,side:tx.side,quantity:q,price:p,tradeDate:tx.tradeDate,charges:c}});const item:Tx={id:String(r.id),broker:"manual",brokerTradeId:String(r.id),symbol:tx.symbol.trim().toUpperCase(),exchange:tx.exchange,company:tx.symbol.trim().toUpperCase(),side:tx.side,quantity:q,price:p,tradeDate:tx.tradeDate,charges:c,source:"manual"};write(accountId,[...read(accountId).filter(x=>x.id!==item.id),item]);setShowTx(false);setTx({...tx,symbol:"",quantity:"",price:"",charges:"0"});await qc.invalidateQueries({queryKey:["portfolio-transactions",accountId]});toast(`${item.side} added and saved`)}catch(e){toast(e instanceof Error?e.message:"Could not save transaction")}}
 async function remove(id:string){if(!confirm("Delete this transaction?"))return;try{await deletePortfolioTransaction({data:{accountId,id}});write(accountId,read(accountId).filter(x=>x.id!==id));await qc.invalidateQueries({queryKey:["portfolio-transactions",accountId]});toast("Transaction deleted")}catch(e){toast(e instanceof Error?e.message:"Could not delete transaction")}}
 if(aq.isLoading)return <div className="py-12 text-center text-sm text-muted">Loading portfolio…</div>;
 return <div className="mx-auto max-w-6xl pb-10">
  <div className="mb-5 flex items-center justify-between gap-3"><div><h1 className="font-display text-3xl tracking-tight">Portfolio</h1><p className="mt-1 text-sm text-muted">Your investments at a glance</p></div><Button onClick={()=>setShowTx(true)} disabled={!active}><Plus className="mr-2 size-4"/>Add Transaction</Button></div>
  <div className="mb-5 flex overflow-x-auto border-b border-border">{accounts.map(a=><button key={a.id} onClick={()=>{setAccountId(a.id);setTab("holdings")}} className={`whitespace-nowrap border-b-2 px-5 py-3 text-sm font-medium ${active?.id===a.id?"border-fg text-fg":"border-transparent text-muted hover:text-fg"}`}>{a.name}</button>)}<button onClick={()=>setShowAdd(true)} className="whitespace-nowrap px-5 py-3 text-sm text-muted"><Plus className="mr-1 inline size-4"/>Add</button></div>
  {editing&&<div className="mb-4 flex gap-2 rounded-xl border border-border bg-surface-2 p-3"><input autoFocus value={editName} onChange={e=>setEditName(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void rename();if(e.key==="Escape")setEditing(null)}} className="flex-1 rounded-lg border bg-bg px-3 py-2 text-sm"/><Button size="sm" onClick={rename}>Save</Button></div>}
  {active&&<>
   <div className="rounded-2xl border border-border bg-bg p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-6"><div><div className="flex items-center gap-2 text-sm font-medium">{active.name}<button onClick={()=>{setEditing(active.id);setEditName(active.name)}} className="text-muted"><Pencil className="size-4"/></button></div><div className="mt-2 text-xs text-muted">Portfolio value</div><div className="mt-1 text-3xl font-semibold tabular">{fmtCurrency(current)}</div></div><div className="text-right"><div className="text-xs text-muted">Overall P&amp;L</div><div className="mt-2 text-2xl font-semibold"><Signed value={pl} as="currency"/></div><div className="mt-1"><Signed value={ret} as="percent"/></div></div></div><div className="mt-6 grid grid-cols-2 gap-4 border-t border-border pt-4 sm:grid-cols-4"><Metric l="Invested value" v={fmtCurrency(invested)}/><Metric l="Current value" v={fmtCurrency(current)}/><Metric l="Unrealised P&amp;L" v={<Signed value={unreal} as="currency"/>}/><Metric l="Realised P&amp;L" v={<Signed value={realized} as="currency"/>}/></div></div>
   <div className="mt-5 flex border-b border-border">{([['holdings',`Holdings ${holdings.length}`],['sold',`Sold ${sold.length}`],['history',`Orders ${transactions.length}`]] as const).map(([v,l])=><button key={v} onClick={()=>setTab(v)} className={`border-b-2 px-5 py-3 text-sm font-medium ${tab===v?"border-fg text-fg":"border-transparent text-muted"}`}>{l}</button>)}</div>
   {tab==="holdings"&&<div className="mt-4 overflow-hidden rounded-2xl border border-border"><div className="hidden grid-cols-7 bg-surface-2 px-4 py-3 text-[11px] font-medium uppercase tracking-wide text-muted md:grid"><span>Stock</span><span>Qty</span><span>Avg. price</span><span>LTP</span><span>Invested</span><span>Current value</span><span className="text-right">P&amp;L</span></div>{holdings.length===0?<div className="p-8"><Empty title="No holdings yet" body="Add a BUY transaction to build your portfolio."/></div>:holdings.map(h=>{const ltp=qm.get(h.symbol)?.price??h.avg,value=h.qty*ltp,p=value-h.invested;return <Link key={`${h.exchange}:${h.symbol}`} to="/stock" search={{symbol:h.symbol,period:"1Y"}} className="grid gap-3 border-t border-border px-4 py-4 hover:bg-surface-2/50 md:grid-cols-7 md:items-center"><div><b>{displaySymbol(h.symbol)}</b><div className="text-xs text-muted">{h.exchange}</div></div><b className="tabular">{trim(h.qty)}</b><b className="tabular">{fmtCurrency(h.avg)}</b><b className="tabular">{fmtCurrency(ltp)}</b><b className="tabular">{fmtCurrency(h.invested)}</b><b className="tabular">{fmtCurrency(value)}</b><div className="text-right"><Signed value={p} as="currency" className="text-sm"/><div className="text-xs"><Signed value={h.invested?p/h.invested*100:null} as="percent"/></div></div></Link>})}</div>}
   {tab!=="holdings"&&<div className="mt-4 space-y-2">{(tab==="sold"?sold:transactions).length===0?<Panel className="p-8"><Empty title={tab==="sold"?"No sold shares":"No orders yet"} body="Your transaction activity will appear here."/></Panel>:(tab==="sold"?sold:transactions).map(t=><Panel key={t.id} className="p-4"><div className="flex justify-between"><div><b>{displaySymbol(t.symbol)}</b><div className="text-xs text-muted">{t.exchange} · {t.tradeDate}</div></div><div className="flex gap-3"><span className={`rounded px-2 py-1 text-xs font-semibold ${t.side==="BUY"?"bg-up/15 text-up":"bg-down/15 text-down"}`}>{t.side}</span><button onClick={()=>remove(t.id)} className="text-muted hover:text-down"><Trash2 className="size-4"/></button></div></div><div className="mt-3 grid grid-cols-3 gap-3 border-t border-border pt-3 text-sm"><Metric l="Qty" v={trim(t.quantity)}/><Metric l="Price" v={fmtCurrency(t.price)}/><Metric l="Value" v={fmtCurrency(t.quantity*t.price)}/></div></Panel>)}</div>}
  </>}
  {showAdd&&<Modal title="Add Portfolio Account" close={()=>setShowAdd(false)}><input autoFocus value={newAccount} onChange={e=>setNewAccount(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void addAccount()}} className="w-full rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Account name"/><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setShowAdd(false)}>Cancel</Button><Button onClick={addAccount}>Add Account</Button></div></Modal>}
  {showTx&&<Modal title="Add Transaction" close={()=>setShowTx(false)}><div className="space-y-3"><input value={tx.symbol} onChange={e=>setTx({...tx,symbol:e.target.value.toUpperCase()})} className="w-full rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Stock symbol e.g. TCS"/><div className="grid grid-cols-2 gap-2"><select value={tx.side} onChange={e=>setTx({...tx,side:e.target.value as "BUY"|"SELL"})} className="rounded-lg border bg-bg px-3 py-2 text-sm"><option>BUY</option><option>SELL</option></select><select value={tx.exchange} onChange={e=>setTx({...tx,exchange:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm"><option>NSE</option><option>BSE</option></select></div><div className="grid grid-cols-2 gap-2"><input type="number" min="0.0001" value={tx.quantity} onChange={e=>setTx({...tx,quantity:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Quantity"/><input type="number" min="0" value={tx.price} onChange={e=>setTx({...tx,price:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Price"/></div><div className="grid grid-cols-2 gap-2"><input type="date" value={tx.tradeDate} onChange={e=>setTx({...tx,tradeDate:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm"/><input type="number" min="0" value={tx.charges} onChange={e=>setTx({...tx,charges:e.target.value})} className="rounded-lg border bg-bg px-3 py-2 text-sm" placeholder="Charges"/></div><Button className="w-full" onClick={saveTx}>Save Transaction</Button></div></Modal>}
 </div>;
}
function Metric({l,v}:{l:string;v:ReactNode}){return <div><div className="text-xs text-muted">{l}</div><div className="mt-1 font-semibold tabular">{v}</div></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><Panel className="w-full max-w-md p-5"><div className="flex justify-between"><h3 className="font-display text-xl">{title}</h3><button onClick={close} className="text-xl text-muted">×</button></div><div className="mt-5">{children}</div></Panel></div>}
function trim(n:number){return Number.isInteger(n)?String(n):n.toFixed(4).replace(/0+$/g,"").replace(/\.$/,"")}
function build(txs:Tx[]):Holding[]{const m=new Map<string,Holding>();for(const t of [...txs].sort((a,b)=>a.tradeDate.localeCompare(b.tradeDate)||a.id.localeCompare(b.id))){const k=`${t.exchange}:${t.symbol}`,h=m.get(k)||{symbol:t.symbol,exchange:t.exchange,qty:0,avg:0,invested:0,realized:0};if(t.side==="BUY"){const nq=h.qty+t.quantity;h.avg=(h.avg*h.qty+t.price*t.quantity)/nq;h.qty=nq;h.invested=h.qty*h.avg}else{h.realized+=t.price*t.quantity-h.avg*t.quantity-t.charges;h.qty=Math.max(0,h.qty-t.quantity);h.invested=h.qty*h.avg}m.set(k,h)}return [...m.values()]}
