import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Search } from "lucide-react";
import { useMemo, useState, useEffect, useRef } from "react";
import { toast } from "sonner";
import { Signed } from "@/components/price";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Empty, Panel, SignalBadge } from "@/components/widgets";
import { displaySymbol, normalizeSymbol } from "@/lib/market/config";
import { customValuation, fmtCurrency, fmtNumber, lastValid, periodHighLow, rsi, sma } from "@/lib/market/math";
import { fetchWatchPack } from "@/lib/market/server";
import { searchStocks } from "@/lib/market/stock-search";
import { useDesk } from "@/lib/store";

export const Route = createFileRoute("/watchlist")({ component: WatchPage });
type WatchFilter = "all" | "normal" | "penny";

function WatchPage() {
  const watchlist=useDesk(s=>s.watchlist); const addWatch=useDesk(s=>s.addWatch); const removeWatch=useDesk(s=>s.removeWatch);
  const [raw,setRaw]=useState(""); const [searchQ,setSearchQ]=useState(""); const [searchOpen,setSearchOpen]=useState(false); const [showDailyAlert,setShowDailyAlert]=useState(false); const [watchFilter,setWatchFilter]=useState<WatchFilter>("all"); const searchBox=useRef<HTMLDivElement>(null);
  useEffect(()=>{const t=window.setTimeout(()=>setSearchQ(raw.trim()),100);return()=>window.clearTimeout(t)},[raw]);
  useEffect(()=>{const onDoc=(e:MouseEvent)=>{if(!searchBox.current?.contains(e.target as Node))setSearchOpen(false)};document.addEventListener("mousedown",onDoc);return()=>document.removeEventListener("mousedown",onDoc)},[]);
  const search=useQuery({queryKey:["watchlist-stock-search",searchQ.toUpperCase()],queryFn:()=>searchStocks({data:{query:searchQ.toUpperCase()}}),enabled:searchQ.length>=3,staleTime:30000,gcTime:5*60000,refetchOnWindowFocus:false,retry:false});
  const pack=useQuery({queryKey:["watch",watchlist],queryFn:()=>fetchWatchPack({data:{symbols:watchlist}}),enabled:watchlist.length>0,refetchInterval:90000});
  const rows=useMemo(()=>{const quotes=new Map((pack.data?.quotes??[]).map(q=>[q.symbol,q]));const hist=new Map((pack.data?.packs??[]).map(p=>[p.symbol,p]));return [...watchlist].sort((a,b)=>displaySymbol(a).localeCompare(displaySymbol(b),undefined,{sensitivity:"base"})).map(symbol=>{const q=quotes.get(symbol);const h=hist.get(symbol);const closes=(h?.bars1y??[]).map(b=>b.c);const s20=lastValid(sma(closes,20));const s50=lastValid(sma(closes,50));const s200=lastValid(sma(closes,200));const r=lastValid(rsi(closes,14));const hl1=periodHighLow(h?.bars1y??[]);const hl5=periodHighLow(h?.bars5y??[]);const val=customValuation(hl5.high,q?.price??null);const price=q?.price??null;const high5y=hl5.high;const buyPrice75=high5y!=null?high5y*0.25:null;const buyPrice90=high5y!=null?high5y*0.10:null;const trigger75=price!=null&&buyPrice75!=null&&price<=buyPrice75;const trigger90=price!=null&&buyPrice90!=null&&price<=buyPrice90;return{symbol,q,s20,s50,s200,r,hl1,hl5,val,buyPrice75,buyPrice90,trigger75,trigger90,signal:val?.signal??null}})},[pack.data,watchlist]);
  // Rule separation: Normal Stock shows ALL watchlist shares with the 75% rule BUY/WAIT status. Penny Stock shows ONLY shares that trigger the 90% rule.
  const filteredRows=useMemo(()=>watchFilter==="penny"?rows.filter(row=>row.trigger90):rows,[rows,watchFilter]);
  const triggered=rows.filter(row=>row.signal);
  useEffect(()=>{if(pack.isLoading||watchlist.length===0)return;const today=new Date().toLocaleDateString("en-CA");const key="artha_watchlist_alert_date";if(localStorage.getItem(key)===today)return;localStorage.setItem(key,today);if(rows.some(row=>row.signal))setShowDailyAlert(true)},[pack.isLoading,watchlist.length,rows]);
  const addSelected=(symbol:string)=>{const added=addWatch(symbol);toast(added?`Added ${displaySymbol(normalizeSymbol(symbol))}`:"Already watching");setRaw("");setSearchQ("");setSearchOpen(false)};
  return <div>
    {showDailyAlert&&triggered.length>0&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="alertdialog" aria-modal="true"><Panel className="w-full max-w-md p-5"><h2 className="text-xl font-semibold">🔔 Watchlist Alert</h2><p className="mt-1 text-sm text-muted">Today’s watchlist triggers:</p><div className="mt-4 space-y-2">{triggered.map(row=><div key={row.symbol} className="flex items-center justify-between rounded-md border p-3"><span className="font-medium">{displaySymbol(row.symbol)}</span><SignalBadge signal={row.signal!}/></div>)}</div><Button className="mt-4 w-full" onClick={()=>setShowDailyAlert(false)}>OK</Button></Panel></div>}
    <div className="flex items-center justify-between gap-3"><div className="min-w-0"><h1 className="font-display text-3xl tracking-tight">Watchlist</h1><p className="mt-1 text-sm text-muted">Live price, 52-week range, RSI and the 25%-of-high rule.</p></div><select value={watchFilter} onChange={e=>setWatchFilter(e.target.value as WatchFilter)} className="h-10 shrink-0 rounded-md border border-border bg-surface-2 px-3 text-sm text-fg outline-none" aria-label="Watchlist stock type"><option value="all">All Stocks</option><option value="normal">Normal Stock · 75% Rule</option><option value="penny">Penny Stock · 90% Rule</option></select></div>
    {watchFilter==="normal"&&<p className="mt-2 text-xs text-muted">All watchlist shares are shown. 75% Rule: BUY ZONE at 25% or less of the 5-year high; otherwise WAIT.</p>}
    {watchFilter==="penny"&&<p className="mt-2 text-xs text-muted">Only watchlist shares that have triggered the 90% rule are shown. 90% Rule: BUY ZONE at 10% or less of the 5-year high.</p>}
    <div ref={searchBox} className="relative mt-5"><form className="flex gap-2" onSubmit={e=>{e.preventDefault();if(!raw.trim())return;addSelected(search.data?.[0]?.symbol??raw.trim())}}><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-subtle"/><Input value={raw} onChange={e=>{setRaw(e.target.value.toUpperCase());setSearchOpen(true)}} onFocus={()=>setSearchOpen(true)} placeholder="RELIANCE, TCS, INFY…" autoCapitalize="characters" autoCorrect="off" spellCheck={false} enterKeyHint="search" className="pl-10" aria-label="Search stock symbol to add to watchlist"/></div><Button type="submit" className="shrink-0">Open</Button></form>{searchOpen&&raw.trim().length>=3&&<div className="absolute z-30 mt-2 w-full overflow-hidden rounded-xl bg-surface-2 shadow-[var(--shadow-border)]">{search.data&&search.data.length>0?<ul>{search.data.map(hit=><li key={hit.symbol}><button type="button" className="flex w-full items-center justify-between gap-3 px-3 py-3 text-left hover:bg-surface-3" onMouseDown={e=>e.preventDefault()} onClick={()=>addSelected(hit.symbol)}><span className="min-w-0"><span className="block text-sm text-fg">{hit.name}</span><span className="block text-xs text-muted">{hit.symbol}</span></span><span className="text-[11px] uppercase tracking-wider text-subtle">{hit.exchange}</span></button></li>)}</ul>:search.isFetching?<div className="px-3 py-3 text-sm text-muted">Searching…</div>:<div className="px-3 py-3 text-sm text-muted">No NSE stocks found.</div>}</div>}</div>
    <div className="mt-5 space-y-2">{filteredRows.length===0?<Empty title={watchFilter==="penny"?"No 90% Rule stocks":"Nothing on the list"} body={watchFilter==="penny"?"No watchlist share has triggered the 90% rule yet.":"Search any NSE stock by typing at least 3 letters."}/>:filteredRows.map(row=><Panel key={row.symbol} className="p-3"><div className="flex items-start justify-between gap-3"><Link to="/stock" search={{symbol:row.symbol,period:"1Y"}} className="min-w-0"><div className="font-medium text-fg">{displaySymbol(row.symbol)}</div><div className="truncate text-xs text-muted">{row.q?.name??row.symbol}</div></Link><div className="text-right"><div className="tabular text-fg">{fmtCurrency(row.q?.price??null)}</div><Signed value={row.q?.changePct??null} as="percent" className="text-xs"/></div></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs text-muted"><span>52W H <span className="tabular text-fg">{fmtCurrency(row.hl1.high??row.q?.high52w??null)}</span></span><span>52W L <span className="tabular text-fg">{fmtCurrency(row.hl1.low??row.q?.low52w??null)}</span></span><span>RSI <span className="tabular text-fg">{fmtNumber(row.r)}</span></span><span>SMA20 <span className="tabular text-fg">{fmtCurrency(row.s20)}</span></span><span>SMA50 <span className="tabular text-fg">{fmtCurrency(row.s50)}</span></span><span>SMA200 <span className="tabular text-fg">{fmtCurrency(row.s200)}</span></span></div><div className="mt-3 flex items-center justify-between gap-2"><div className="flex flex-wrap items-center gap-2">{watchFilter==="normal"?<SignalBadge signal={row.trigger75?"BUY":"WAIT"}/>:watchFilter==="penny"?<SignalBadge signal={row.trigger90?"BUY":"WAIT"}/>:row.signal?<SignalBadge signal={row.signal}/>:<span className="text-xs text-subtle">No signal</span>}</div><Button variant="ghost" size="sm" className="h-10" onClick={()=>removeWatch(row.symbol)}>Remove</Button></div></Panel>)}</div>
  </div>;
}
