import { useState } from "react";
import { ArrowLeft, ExternalLink, RefreshCw, TrendingUp, AlertTriangle, Building2, IndianRupee, Globe, FileText, LineChart, PieChart, Info } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Panel } from "@/components/widgets";
import { cn } from "@/lib/utils";
import type { IpoRecord } from "@/lib/ipo/types";

const money=(v:number|null|undefined)=>v==null?"માહિતી ઉપલબ્ધ નથી":"₹"+v.toLocaleString("en-IN",{maximumFractionDigits:2});
const crore=(v:number|null|undefined)=>v==null?"માહિતી ઉપલબ્ધ નથી":"₹"+v.toLocaleString("en-IN",{maximumFractionDigits:2})+" કરોડ";
const mult=(v:number|null|undefined)=>v==null?"માહિતી ઉપલબ્ધ નથી":v.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})+" ગણું";
const date=(v:string|null|undefined)=>v?new Date(v+"T00:00:00").toLocaleDateString("gu-IN",{day:"2-digit",month:"short",year:"numeric"}):"માહિતી ઉપલબ્ધ નથી";
const typeLabel=(v:string)=>v==="Mainboard"?"મેઇનબોર્ડ":"એસએમઈ";
function status(ipo:IpoRecord){const t=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());if(ipo.listingDate&&t>=ipo.listingDate)return"લિસ્ટેડ";if(ipo.openDate&&t<ipo.openDate)return"આગામી";if(ipo.closeDate&&t>ipo.closeDate)return"બંધ";return"ખુલ્લું";}
function Source({label,url}:{label:string;url:string}){return <a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-surface-2 px-3 py-2 text-xs text-fg hover:bg-accent/10">{label}<ExternalLink className="size-3 text-muted"/></a>}
function Metric({label,value}:{label:string;value:string}){return <Panel className="p-3"><div className="text-[10px] uppercase tracking-wide text-subtle">{label}</div><div className="mt-1 truncate text-sm font-medium tabular">{value}</div></Panel>}
function Table({rows}:{rows:Array<[string,string]>}){return <Panel className="p-4"><div className="overflow-x-auto"><table className="w-full text-xs"><tbody>{rows.map((r,i)=><tr key={r[0]+i} className="border-b border-border last:border-0"><td className="py-2 pr-4 text-muted">{r[0]}</td><td className="py-2 text-right font-medium text-fg">{r[1]}</td></tr>)}</tbody></table></div></Panel>}
function Empty(){return <Panel className="p-6 text-center"><Info className="mx-auto size-7 text-muted"/><p className="mt-2 text-xs text-muted">ચકાસાયેલ માહિતી ઉપલબ્ધ નથી.</p></Panel>}
function Heading({icon:Icon,text}:{icon:any;text:string}){return <div className="mb-3 flex items-center gap-2"><Icon className="size-4 text-accent"/><h2 className="text-sm font-semibold">{text}</h2></div>}

export function ArthaIpoDetail({ipo,onRefresh}:{ipo:IpoRecord;onRefresh:()=>void}){
 const [tab,setTab]=useState("q1");
 const tabs=[["q1","Q1"],["q2","Q2"],["q3","Q3"],["q4","Q4"],["q5","Q5"],["q6","Q6"],["q7","Q7"],["q8","Q8"],["q9","Q9"]];
 const estimate=ipo.gmpRs!=null&&ipo.priceHigh!=null?ipo.priceHigh+ipo.gmpRs:null;
 return <div>
  <div className="flex items-center justify-between"><Link to="/ipo" search={{}} className="inline-flex items-center gap-2 text-sm text-muted"><ArrowLeft className="size-4"/> IPO</Link><button onClick={onRefresh} type="button" className="inline-flex size-10 items-center justify-center rounded-lg bg-surface-2 text-muted"><RefreshCw className="size-4"/></button></div>
  <div className="mt-5 flex flex-wrap items-start justify-between gap-3"><div><h1 className="font-display text-2xl tracking-tight">{ipo.name} IPO</h1><div className="mt-2 flex flex-wrap gap-2"><span className="rounded-full bg-accent/15 px-2.5 py-1 text-[10px] font-semibold text-accent">{typeLabel(ipo.type)}</span><span className="rounded-full bg-surface-2 px-2.5 py-1 text-[10px] font-semibold text-muted">{status(ipo)}</span><span className="rounded-full bg-surface-2 px-2.5 py-1 text-[10px] font-semibold text-muted">{ipo.exchange}</span></div></div><div className="flex flex-wrap gap-2">{ipo.officialWebsite&&<Source label="Official Website" url={ipo.officialWebsite}/>} {ipo.rhpUrl&&<Source label="RHP" url={ipo.rhpUrl}/>} {ipo.drhpUrl&&<Source label="DRHP" url={ipo.drhpUrl}/>} {ipo.prospectusUrl&&<Source label={ipo.prospectusType||"Prospectus"} url={ipo.prospectusUrl}/>} {ipo.nsePageUrl&&<Source label="NSE" url={ipo.nsePageUrl}/>} {ipo.bsePageUrl&&<Source label="BSE" url={ipo.bsePageUrl}/>} {ipo.sebiUrl&&<Source label="SEBI" url={ipo.sebiUrl}/>}</div></div>
  <div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4"><Metric label="Price Band" value={ipo.priceBand||"માહિતી ઉપલબ્ધ નથી"}/><Metric label="Lot Size" value={ipo.lotSize==null?"માહિતી ઉપલબ્ધ નથી":ipo.lotSize.toLocaleString("en-IN")}/><Metric label="Issue Size" value={crore(ipo.issueSize)}/><Metric label="Minimum Application" value={money(ipo.verifiedMinApplication??ipo.minSubscription)}/></div>
  <div className="mt-2 grid grid-cols-2 gap-2 md:grid-cols-4"><Metric label="Open" value={date(ipo.openDate)}/><Metric label="Close" value={date(ipo.closeDate)}/><Metric label="Listing" value={date(ipo.listingDate)}/><Metric label="Face Value" value={money(ipo.faceValue)}/></div>
  <div className="mt-4 grid gap-3 md:grid-cols-2">
   <Panel className="p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-medium"><TrendingUp className="size-4 text-up"/>Subscription</span><span className="tabular text-xl font-semibold text-up">{mult(ipo.subscription)}</span></div><div className="mt-3 space-y-2">{ipo.subscriptionCategories.map((x,i)=><div key={x.category+i} className="flex justify-between rounded-lg bg-surface-2 px-3 py-2 text-xs"><span className="text-muted">{x.category}</span><span className="tabular">{mult(x.multiple)}</span></div>)}</div><div className="mt-3 border-t border-border pt-2 text-[10px] text-subtle">Source: {ipo.subscriptionSource||"માહિતી ઉપલબ્ધ નથી"}{ipo.subscriptionTimestamp?" • "+new Date(ipo.subscriptionTimestamp).toLocaleString("gu-IN"):""}</div></Panel>
   <Panel className="p-4"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm font-medium"><AlertTriangle className="size-4 text-warn"/>GMP (અનૌપચારિક)</span><span className="tabular text-xl font-semibold">{ipo.gmpRs==null?"માહિતી ઉપલબ્ધ નથી":"₹"+ipo.gmpRs}</span></div><div className="mt-2 flex justify-between text-xs"><span className="text-muted">GMP %</span><span className="tabular">{ipo.gmpPct==null?"માહિતી ઉપલબ્ધ નથી":ipo.gmpPct+"%"}</span></div><div className="mt-3 space-y-2">{ipo.gmpSources.map((x,i)=><div key={x.source+i} className="flex justify-between rounded-lg bg-surface-2 px-3 py-2 text-xs"><span>{x.source}</span><span>{x.rs==null?"—":"₹"+x.rs}{x.pct!=null?" ("+x.pct+"%)":""}</span></div>)}</div><p className="mt-3 border-t border-border pt-2 text-[10px] text-subtle">GMP grey-market માહિતી છે; લિસ્ટિંગ ભાવની ખાતરી નથી.</p></Panel>
  </div>
  <div className="mt-5 overflow-x-auto"><div className="flex min-w-max gap-1 rounded-xl bg-surface-2 p-1">{tabs.map(([k,n])=><button key={k} type="button" onClick={()=>setTab(k)} className={cn("rounded-lg px-3 py-2 text-xs font-medium",tab===k?"bg-accent text-accent-foreground":"text-muted hover:text-fg")}>{n}</button>)}</div></div>
  <div className="mt-4">
   {tab==="q1"&&<div className="space-y-3"><Table rows={[["કંપની",ipo.name],["IPO પ્રકાર",typeLabel(ipo.type)],["Exchange",ipo.exchange],["Status",status(ipo)],["Open Date",date(ipo.openDate)],["Close Date",date(ipo.closeDate)],["Listing Date",date(ipo.listingDate)],["Price Band",ipo.priceBand||"માહિતી ઉપલબ્ધ નથી"],["Face Value",money(ipo.faceValue)],["Lot Size",ipo.lotSize==null?"માહિતી ઉપલબ્ધ નથી":ipo.lotSize.toLocaleString("en-IN")],["Minimum Application",money(ipo.verifiedMinApplication??ipo.minSubscription)],["Issue Size",crore(ipo.issueSize)],["Issue Type",ipo.issueType||"માહિતી ઉપલબ્ધ નથી"],["Fresh Issue",crore(ipo.freshIssue)],["Fresh Issue Shares",ipo.freshIssueShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.freshIssueShares.toLocaleString("en-IN")],["OFS",crore(ipo.offerForSale)],["OFS Shares",ipo.offerForSaleShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.offerForSaleShares.toLocaleString("en-IN")],["Promoter Holding Pre",ipo.promoterHolding==null?"માહિતી ઉપલબ્ધ નથી":ipo.promoterHolding+"%"],["Promoter Holding Post",ipo.postIssuePromoterHolding==null?"માહિતી ઉપલબ્ધ નથી":ipo.postIssuePromoterHolding+"%"]]}/>{ipo.documents.length>0&&<Panel className="p-4"><Heading icon={FileText} text="Prospectus / Documents"/><div className="flex flex-wrap gap-2">{ipo.documents.map((d,i)=><Source key={d.url+i} label={d.label} url={d.url}/>)}</div></Panel>}</div>}
   {tab==="q2"&&(ipo.business||ipo.sector||ipo.products.length||ipo.segments.length?<div className="space-y-3"><Table rows={[["Industry / Sector",ipo.sector||"માહિતી ઉપલબ્ધ નથી"],["Location",ipo.city&&ipo.state?ipo.city+", "+ipo.state:ipo.city||ipo.state||"માહિતી ઉપલબ્ધ નથી"],["Business",ipo.business||"માહિતી ઉપલબ્ધ નથી"],["Business Model",ipo.businessModel||"માહિતી ઉપલબ્ધ નથી"],["Registered Office",ipo.registeredOffice||"માહિતી ઉપલબ્ધ નથી"],["Corporate Office",ipo.corporateOffice||"માહિતી ઉપલબ્ધ નથી"],["Products",ipo.products.length?ipo.products.join(", "):"માહિતી ઉપલબ્ધ નથી"],["Services",ipo.services.length?ipo.services.join(", "):"માહિતી ઉપલબ્ધ નથી"],["Business Locations",ipo.businessLocations.length?ipo.businessLocations.join(", "):"માહિતી ઉપલબ્ધ નથી"],["Segments",ipo.segments.length?ipo.segments.join(", "):"માહિતી ઉપલબ્ધ નથી"]]}/>{ipo.promoters.length>0&&<Panel className="p-4"><Heading icon={Building2} text="Promoters"/><div className="flex flex-wrap gap-2">{ipo.promoters.map(x=><span key={x} className="rounded-full bg-surface-2 px-2.5 py-1 text-xs">{x}</span>)}</div></Panel>}</div>:<Empty/>)}
   {tab==="q3"&&(ipo.business||ipo.countries.length||ipo.competitors.length?<div className="space-y-3"><Table rows={[["Business / Customer context",ipo.business||"માહિતી ઉપલબ્ધ નથી"],["Customer Model",[ipo.b2b&&"B2B",ipo.b2c&&"B2C"].filter(Boolean).join(" / ")||"માહિતી ઉપલબ્ધ નથી"],["B2B",ipo.b2b==null?"માહિતી ઉપલબ્ધ નથી":ipo.b2b?"હા":"ના"],["B2C",ipo.b2c==null?"માહિતી ઉપલબ્ધ નથી":ipo.b2c?"હા":"ના"],["Domestic Market",ipo.domesticMarket==null?"માહિતી ઉપલબ્ધ નથી":ipo.domesticMarket?"હા":"ના"],["Export Market",ipo.exportMarket==null?"માહિતી ઉપલબ્ધ નથી":ipo.exportMarket?"હા":"ના"],["Customer Concentration",ipo.customerConcentration||"માહિતી ઉપલબ્ધ નથી"],["Customer Categories",ipo.customerCategories.length?ipo.customerCategories.join(", "):"માહિતી ઉપલબ્ધ નથી"],["Industries Served",ipo.industriesServed.length?ipo.industriesServed.join(", "):"માહિતી ઉપલબ્ધ નથી"],["Geographic Presence",ipo.geographicPresence.length?ipo.geographicPresence.join(", "):"માહિતી ઉપલબ્ધ નથી"],["Countries / Markets",ipo.countryCount!=null?String(ipo.countryCount):String(ipo.countries.length)],["Market / Competition",ipo.competitors.length?ipo.competitors.join(", "):"માહિતી ઉપલબ્ધ નથી"]]}/>{ipo.countries.length>0&&<Panel className="p-4"><Heading icon={Globe} text="Markets / Countries"/><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-border"><th className="py-2 text-left">Country</th><th className="py-2 text-left">Business</th><th className="py-2 text-right">Sales %</th></tr></thead><tbody>{ipo.countries.map((x,i)=><tr key={x.country+i} className="border-b border-border"><td className="py-2">{x.country}</td><td className="py-2 text-muted">{x.business}</td><td className="py-2 text-right">{x.salesPct==null?"જાહેર નથી":x.salesPct+"%"}</td></tr>)}</tbody></table></div></Panel>}</div>:<Empty/>)}
   {tab==="q4"&&(ipo.revenues.length||ipo.revenueSources.length||ipo.countries.length?<div className="space-y-3">{ipo.revenueSources.length>0&&<Panel className="p-4"><Heading icon={PieChart} text="Revenue Sources / Segments"/><div className="space-y-2">{ipo.revenueSources.map((x,i)=><div key={x.segment+i} className="flex justify-between rounded-lg bg-surface-2 px-3 py-2 text-xs"><span>{x.segment}</span><span>{x.amount==null?"માહિતી ઉપલબ્ધ નથી":crore(x.amount)} {x.percentage==null?"":"• "+x.percentage+"%"}</span></div>)}</div><div className="mt-3 text-xs text-muted">Domestic: {ipo.domesticRevenuePercent==null?"માહિતી ઉપલબ્ધ નથી":ipo.domesticRevenuePercent+"%"} • Export: {ipo.exportRevenuePercent==null?"માહિતી ઉપલબ્ધ નથી":ipo.exportRevenuePercent+"%"}</div></Panel>}<Panel className="p-4"><Heading icon={PieChart} text="Revenue Trend"/><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-border"><th className="py-2 text-left">Year</th><th className="py-2 text-right">Revenue</th></tr></thead><tbody>{ipo.revenues.map((x,i)=><tr key={x.year+i} className="border-b border-border"><td className="py-2">{x.year}</td><td className="py-2 text-right">{crore(x.value)}</td></tr>)}</tbody></table></div></Panel><Table rows={[["Countries / Markets",ipo.countryCount!=null?String(ipo.countryCount):String(ipo.countries.length)],["Country-wise sales",ipo.countries.length?ipo.countries.map(x=>x.country+": "+(x.salesPct==null?"જાહેર નથી":x.salesPct+"%")).join(" • "):"માહિતી ઉપલબ્ધ નથી"]]}/></div>:<Empty/>)}
   {tab==="q5"&&<Financials ipo={ipo}/>}
   {tab==="q6"&&<Table rows={[["Price Band",ipo.priceBand||"માહિતી ઉપલબ્ધ નથી"],["Face Value",money(ipo.faceValue)],["Lot Size",ipo.lotSize==null?"માહિતી ઉપલબ્ધ નથી":ipo.lotSize.toLocaleString("en-IN")],["Minimum Application",money(ipo.verifiedMinApplication??ipo.minSubscription)],["Total Issue Size",crore(ipo.issueSize)],["Fresh Issue",crore(ipo.freshIssue)],["Fresh Issue Shares",ipo.freshIssueShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.freshIssueShares.toLocaleString("en-IN")],["OFS",crore(ipo.offerForSale)],["OFS Shares",ipo.offerForSaleShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.offerForSaleShares.toLocaleString("en-IN")],["Total Shares Offered",ipo.sharesOffered==null?"માહિતી ઉપલબ્ધ નથી":ipo.sharesOffered.toLocaleString("en-IN")],["QIB Shares",ipo.qibShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.qibShares.toLocaleString("en-IN")],["NII Shares",ipo.niiShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.niiShares.toLocaleString("en-IN")],["Retail Shares",ipo.retailShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.retailShares.toLocaleString("en-IN")],["Employee Shares",ipo.employeeShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.employeeShares.toLocaleString("en-IN")],["Anchor Shares",ipo.anchorShares==null?"માહિતી ઉપલબ્ધ નથી":ipo.anchorShares.toLocaleString("en-IN")],["Promoter Holding Pre",ipo.promoterHolding==null?"માહિતી ઉપલબ્ધ નથી":ipo.promoterHolding+"%"],["Promoter Holding Post",ipo.postIssuePromoterHolding==null?"માહિતી ઉપલબ્ધ નથી":ipo.postIssuePromoterHolding+"%"]]}/>}
   {tab==="q7"&&<div className="space-y-3"><Panel className="p-4"><Heading icon={IndianRupee} text="IPO Moneyનો ઉપયોગ"/>{ipo.objects.length?<ul className="space-y-2 text-xs">{ipo.objects.map((x,i)=><li key={i} className="rounded-lg bg-surface-2 p-3">{x}</li>)}</ul>:<p className="text-xs text-muted">Objects of Issue માટે માહિતી ઉપલબ્ધ નથી.</p>}</Panel><Panel className="p-4"><Heading icon={AlertTriangle} text="મુખ્ય Risks"/>{ipo.risks.length?<ul className="space-y-2 text-xs">{ipo.risks.map((x,i)=><li key={i} className="rounded-lg border border-border p-3">{x}</li>)}</ul>:<p className="text-xs text-muted">ચકાસાયેલ risk factors ઉપલબ્ધ નથી.</p>}</Panel></div>}
   {tab==="q8"&&<div className="space-y-3"><Panel className="p-4"><Heading icon={AlertTriangle} text="GMP Sources"/>{ipo.gmpSources.length?<div className="space-y-2">{ipo.gmpSources.map((x,i)=><div key={x.source+i} className="flex justify-between rounded-lg bg-surface-2 px-3 py-2 text-xs"><span>{x.source} <span className="text-[10px] text-subtle">{x.asOf||""}</span></span><span>{x.rs==null?"—":"₹"+x.rs}{x.pct!=null?" ("+x.pct+"%)":""}</span></div>)}</div>:<p className="text-xs text-muted">હાલ ચકાસી શકાય એવો GMP ઉપલબ્ધ નથી.</p>}</Panel><Panel className="p-4"><Heading icon={TrendingUp} text="Expected Listing Indicator"/><Table rows={[["Current GMP",ipo.gmpRs==null?"માહિતી ઉપલબ્ધ નથી":"₹"+ipo.gmpRs],["GMP %",ipo.gmpPct==null?"માહિતી ઉપલબ્ધ નથી":ipo.gmpPct+"%"],["GMP-based indication",estimate==null?"ગણતરી ઉપલબ્ધ નથી":"₹"+estimate.toLocaleString("en-IN")]]}/><p className="mt-3 text-[10px] text-subtle">GMP અનૌપચારિક છે; Expected listing માત્ર GMP આધારિત indication છે, guarantee નથી.</p></Panel></div>}
   {tab==="q9"&&<div className="space-y-3"><Table rows={[["Registrar",ipo.registrar||"માહિતી ઉપલબ્ધ નથી"],["Registrar Address",ipo.registrarAddress||"માહિતી ઉપલબ્ધ નથી"],["Registrar Email",ipo.registrarEmail||"માહિતી ઉપલબ્ધ નથી"],["Registrar Phone",ipo.registrarPhone||"માહિતી ઉપલબ્ધ નથી"],["Lead Managers",ipo.leadManagers.length?ipo.leadManagers.join(", "):"માહિતી ઉપલબ્ધ નથી"],["Sponsor Bank",ipo.sponsorBank||"માહિતી ઉપલબ્ધ નથી"],["Market Maker",ipo.marketMaker||"માહિતી ઉપલબ્ધ નથી"]]}/><div className="flex flex-wrap gap-2">{ipo.registrarWebsite&&<Source label="Registrar Website" url={ipo.registrarWebsite}/>} {ipo.allotmentCheckUrl&&<Source label="Allotment Status" url={ipo.allotmentCheckUrl}/>} {ipo.scsbListUrl&&<Source label="SCSB List" url={ipo.scsbListUrl}/>}</div></div>}
  </div>
  <div className="mt-4 text-[10px] text-subtle">ચકાસણી: {ipo.verifiedAt?new Date(ipo.verifiedAt).toLocaleString("gu-IN"):"માહિતી ઉપલબ્ધ નથી"} • સ્રોત: {[...new Set(ipo.verifiedSources)].join(", ")||"માહિતી ઉપલબ્ધ નથી"}</div>
 </div>
}
function Financials({ipo}:{ipo:IpoRecord}){if(!ipo.financials.length&&!ipo.revenues.length&&!ipo.profits.length&&!ipo.eps.length)return <Empty/>;const rows=ipo.financials.length?ipo.financials:[...new Set([...ipo.revenues.map(x=>x.year),...ipo.profits.map(x=>x.year),...ipo.eps.map(x=>x.year)])].map(y=>({year:y,revenue:ipo.revenues.find(x=>x.year===y)?.value??null,pat:ipo.profits.find(x=>x.year===y)?.value??null,eps:ipo.eps.find(x=>x.year===y)?.value??null,ebitda:null,debt:null,netWorth:null,assets:null,roe:null,roce:null}));return <Panel className="p-4"><Heading icon={LineChart} text="Financial Performance"/><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-xs"><thead><tr className="border-b border-border"><th className="py-2 text-left">Year</th><th className="py-2 text-right">Revenue</th><th className="py-2 text-right">Profit</th><th className="py-2 text-right">EPS</th><th className="py-2 text-right">EBITDA</th><th className="py-2 text-right">ROE</th><th className="py-2 text-right">Debt</th><th className="py-2 text-right">Net Worth</th><th className="py-2 text-right">Assets</th><th className="py-2 text-right">ROCE</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.year} className="border-b border-border"><td className="py-2">{x.year}</td><td className="py-2 text-right">{crore(x.revenue)}</td><td className="py-2 text-right">{crore(x.pat)}</td><td className="py-2 text-right">{x.eps==null?"માહિતી ઉપલબ્ધ નથી":"₹"+x.eps}</td><td className="py-2 text-right">{crore(x.ebitda)}</td><td className="py-2 text-right">{x.roe==null?"—":x.roe+"%"}</td><td className="py-2 text-right">{crore(x.debt)}</td><td className="py-2 text-right">{crore(x.netWorth)}</td><td className="py-2 text-right">{crore(x.assets)}</td><td className="py-2 text-right">{x.roce==null?"—":x.roce+"%"}</td></tr>)}</tbody></table></div></Panel>}
