import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { fetchOwnership } from "@/lib/market/ownership";
import { cn } from "@/lib/utils";
import { Panel } from "./widgets";

type Row={period:string;promoter:number|null;fii:number|null;dii:number|null;public:number|null;others:number|null;pledged:number|null;unpledged:number|null};
function pct(v:number|null){return v==null?"—":`${v.toFixed(2)}%`;}
function shortPeriod(p:string){const d=new Date(p); return Number.isNaN(d.getTime())?p:d.toLocaleDateString("en-IN",{month:"short",year:"numeric"});}
function Bar({label,value,max=100}:{label:string;value:number|null;max?:number}){const v=value??0; return <div className="min-w-[58px] flex-1"><div className="flex h-36 items-end justify-center"><div title={`${label}: ${pct(value)}`} className="w-8 rounded-t-md bg-accent" style={{height:`${Math.max(2,Math.min(100,v/max*100))}%`}}/></div><div className="mt-1 text-center text-[10px] font-medium text-fg">{pct(value)}</div><div className="mt-1 text-center text-[9px] text-subtle">{label}</div></div>}
function Chart({row,kind}:{row:Row;kind:"holding"|"pledge"}){const bars=kind==="holding"?[ ["Promoter",row.promoter],["FII/FPI",row.fii],["DII",row.dii],["Public",row.public],["Others",row.others] ] as [string,number|null][]:[["Pledged",row.pledged],["Unpledged",row.unpledged]] as [string,number|null][]; return <Panel className="mt-3 p-3"><div className="mb-2 text-xs text-muted">{shortPeriod(row.period)}</div><div className="flex gap-2">{bars.map(([label,value])=><Bar key={label} label={label} value={value}/>)}</div></Panel>}
export function OwnershipHistory({symbol}:{symbol:string}){const q=useQuery({queryKey:["ownership",symbol],queryFn:()=>fetchOwnership({data:{symbol}}),staleTime:15*60_000,refetchOnWindowFocus:false}); const [view,setView]=useState<"quarterly"|"5y">("quarterly"); const [tab,setTab]=useState<"holding"|"pledge">("holding"); const rows=q.data?.[view==="quarterly"?"quarters":"years"]??[]; const latest=q.data?.latest; return <div className="mt-4"><div className="mb-2 flex items-center justify-between"><h3 className="font-display text-lg">Shareholding & Pledge</h3><span className="text-[10px] text-subtle">NSE · auto-updated</span></div><div className="flex gap-1 overflow-x-auto pb-1">{([["holding","Shareholding"],["pledge","Pledge"]] as const).map(([v,l])=><button key={v} type="button" onClick={()=>setTab(v)} className={cn("h-9 rounded-full px-3 text-xs font-medium",tab===v?"bg-accent text-accent-fg":"bg-surface-2 text-muted")}>{l}</button>)}<span className="mx-1 w-px bg-border"/>{([["quarterly","Quarterly"],["5y","5 YEARS"]] as const).map(([v,l])=><button key={v} type="button" onClick={()=>setView(v)} className={cn("h-9 rounded-full px-3 text-xs font-medium",view===v?"bg-accent text-accent-fg":"bg-surface-2 text-muted")}>{l}</button>)}</div>{q.isFetching?<Panel className="mt-3 p-4 text-sm text-muted">Latest NSE ownership data loading…</Panel>:rows.length===0?<Panel className="mt-3 p-4 text-sm text-muted">Ownership data is not available for this stock yet.</Panel>:<div className="space-y-2">{rows.map((row)=><Chart key={row.period} row={row} kind={tab}/>)}</div>}<div className="mt-2 text-[10px] text-subtle">Latest available filing: {latest?shortPeriod(latest):"—"}. Figures are percentages; quarterly filings can arrive after quarter-end.</div></div>;
}
