import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { fetchOwnership } from "@/lib/market/ownership";
import { cn } from "@/lib/utils";
import { Panel } from "./widgets";

type Row={period:string;promoter:number|null;fii:number|null;dii:number|null;public:number|null;others:number|null;pledged:number|null;unpledged:number|null};
const pct=(v:number|null)=>v==null?"—":`${v.toFixed(2)}%`;
const dateOf=(p:string)=>{const d=new Date(p);return Number.isNaN(d.getTime())?null:d;};
const quarterOf=(p:string)=>{const d=dateOf(p),m=d?.getUTCMonth()??-1;return m===5?"Q1":m===8?"Q2":m===11?"Q3":m===2?"Q4":null;};
const periodLabel=(p:string)=>{const d=dateOf(p);return d?d.toLocaleDateString("en-IN",{month:"short",year:"numeric"}):p;};
function Bar({label,value}:{label:string;value:number|null}){const v=Math.max(0,Math.min(100,value??0));return <div className="min-w-[62px] flex-1"><div className="flex h-40 items-end justify-center"><div className="w-9 rounded-t-md bg-accent" style={{height:`${Math.max(2,v)}%`}} title={`${label}: ${pct(value)}`}/></div><div className="mt-1 text-center text-[10px] font-semibold text-fg">{pct(value)}</div><div className="mt-1 text-center text-[9px] text-subtle">{label}</div></div>}
function OneQuarter({row,kind}:{row:Row;kind:"holding"|"pledge"}){const bars=kind==="holding"?[["Promoter",row.promoter],["FII/FPI",row.fii],["DII",row.dii],["Public",row.public],["Others",row.others]]:[["Pledged",row.pledged],["Unpledged",row.unpledged]];return <Panel className="mt-3 p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium text-fg">{periodLabel(row.period)}</span><span className="text-[10px] text-subtle">Quarterly</span></div><div className="flex gap-2">{bars.map(([label,value])=><Bar key={label} label={label as string} value={value as number|null}/>)}</div></Panel>}
function FiveYear({rows,kind}:{rows:Row[];kind:"holding"|"pledge"}){const cats=kind==="holding"?[["Promoter","promoter"],["FII/FPI","fii"],["DII","dii"],["Public","public"],["Others","others"]]:[["Pledged","pledged"],["Unpledged","unpledged"]];return <Panel className="mt-3 overflow-x-auto p-3"><div className="mb-2 text-xs text-muted">Last 5 available years</div><div className="flex min-w-[620px] gap-4">{rows.map(row=><div key={row.period} className="flex-1"><div className="mb-2 text-center text-xs font-semibold text-fg">{dateOf(row.period)?.getUTCFullYear()??row.period}</div><div className="flex h-40 items-end justify-center gap-1">{cats.map(([label,key])=>{const value=row[key as keyof Row] as number|null;const v=Math.max(0,Math.min(100,value??0));return <div key={key} className="w-5 rounded-t-sm bg-accent" style={{height:`${Math.max(2,v)}%`}} title={`${label}: ${pct(value)}`}/>})}</div><div className="mt-1 text-center text-[9px] text-subtle">{periodLabel(row.period)}</div></div>)}</div><div className="mt-3 flex flex-wrap gap-3 text-[10px] text-subtle">{cats.map(([label])=><span key={label}>▮ {label}</span>)}</div></Panel>}
export function OwnershipHistory({symbol}:{symbol:string}){const q=useQuery({queryKey:["ownership",symbol],queryFn:()=>fetchOwnership({data:{symbol}}),staleTime:15*60_000,refetchOnWindowFocus:false});const [view,setView]=useState<"quarterly"|"5y">("quarterly");const [tab,setTab]=useState<"holding"|"pledge">("holding");const [quarter,setQuarter]=useState<"Q1"|"Q2"|"Q3"|"Q4">("Q4");const rows=q.data?.[view==="quarterly"?"quarters":"years"]??[];const selected=rows.filter(r=>quarterOf(r.period)===quarter).at(-1)??rows.at(-1);const latest=q.data?.latest;return <div className="mt-4"><div className="mb-2 flex items-center justify-between"><h3 className="font-display text-lg">Shareholding & Pledge</h3><span className="text-[10px] text-subtle">NSE · automatic latest data</span></div><div className="flex gap-1 overflow-x-auto pb-1">{([["holding","Shareholding"],["pledge","Pledge"]] as const).map(([v,l])=><button key={v} type="button" onClick={()=>setTab(v)} className={cn("h-9 rounded-full px-3 text-xs font-medium",tab===v?"bg-accent text-accent-fg":"bg-surface-2 text-muted")}>{l}</button>)}<span className="mx-1 w-px bg-border"/>{([["Q1","Q1"],["Q2","Q2"],["Q3","Q3"],["Q4","Q4"],["5y","5 YEARS"]] as const).map(([v,l])=><button key={v} type="button" onClick={()=>v==="5y"?setView("5y"):(setView("quarterly"),setQuarter(v as "Q1"|"Q2"|"Q3"|"Q4"))} className={cn("h-9 rounded-full px-3 text-xs font-medium",(view==="5y"&&v==="5y")||(view==="quarterly"&&v===quarter)?"bg-accent text-accent-fg":"bg-surface-2 text-muted")}>{l}</button>)}</div>{q.isFetching?<Panel className="mt-3 p-4 text-sm text-muted">Latest NSE ownership data loading…</Panel>:view==="5y"?(q.data?.years?.length?<FiveYear rows={q.data.years} kind={tab}/>:<Panel className="mt-3 p-4 text-sm text-muted">5-year ownership history is not available yet.</Panel>):(selected?<OneQuarter row={selected} kind={tab}/>:<Panel className="mt-3 p-4 text-sm text-muted">Quarterly ownership data is not available yet.</Panel>)}<div className="mt-2 text-[10px] text-subtle">Latest available filing: {latest?periodLabel(latest):"—"}. Source: NSE corporate shareholding filings.</div></div>}
