import { cached } from "../cache";
import { extractLinks, parseHtmlTables, visibleText } from "../html";
import { fetchText } from "../http";
import { allotmentUrlForRegistrar } from "../registrars";
import { clean, namesMatch, normalizeCompanyName, num, parseDate, parsePriceBand } from "../text";
import type { FinancialYear, IpoRecord } from "../types";

const LIST_URL="https://www.chittorgarh.com/report/ipo-in-india-list-main-board-sme/82/";
export interface ChittorIndexItem{name:string;url:string}
export async function fetchChittorgarhIndex():Promise<ChittorIndexItem[]>{return cached("chittor:index",1800000,async()=>{const html=await fetchText(LIST_URL,{timeoutMs:12000});return extractLinks(html,/\/ipo\/[a-z0-9-]+-ipo\/\d+/i).map(l=>({name:l.text,url:l.href.startsWith("http")?l.href:`https://www.chittorgarh.com${l.href}`})).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i);});}
export function matchChittorgarhUrl(index:ChittorIndexItem[],name:string){const hit=index.find(x=>namesMatch(x.name.replace(/ipo/gi," "),name)||namesMatch(x.url,name));if(hit)return hit.url;const slug=normalizeCompanyName(name).replace(/\s+/g,"-");return index.find(x=>x.url.includes(slug)||x.url.includes(slug.slice(0,18)))?.url??null;}
function rows(html:string){return parseHtmlTables(html);}
function find(tables:string[][][],rx:RegExp){return tables.find(t=>t.some(r=>r.some(c=>rx.test(c))))??null;}
function financials(table:string[][]|null):FinancialYear[]{if(!table||table.length<2)return[];const years=table[0].slice(1).map(clean).filter(x=>/20\d{2}|mar|dec|jan/i.test(x));const pick=(rx:RegExp)=>{const r=table.find(x=>rx.test(x[0]||""));return years.map((_,i)=>r?num(r[i+1]):null)};return years.map((year,i)=>({year,revenue:pick(/revenue|turnover|total income/i)[i],ebitda:pick(/ebitda/i)[i],pat:pick(/profit after tax|net profit|^pat$/i)[i],eps:pick(/^eps/i)[i],debt:pick(/debt|borrow/i)[i],netWorth:pick(/net worth|networth/i)[i],assets:pick(/^assets|total assets/i)[i],roe:pick(/roe|ronw|return on/i)[i],roce:pick(/roce/i)[i],source:"Chittorgarh"}));}
export function parseChittorgarhDetail(html:string,pageUrl:string):Partial<IpoRecord>{const text=visibleText(html),tables=rows(html),all=text;const band=parsePriceBand((all.match(/Price Band\s*[:\-]?\s*₹?\s*([\d,]+\s*[-–]\s*[\d,]+)/i)?.[1]??""));const lot=num(all.match(/Lot Size\s*[:\-]?\s*([\d,]+)/i)?.[1]??null),listing=parseDate(all.match(/Listing Date\s*[:\-]?\s*([A-Za-z]{3,}\s+\d{1,2},?\s+\d{4})/i)?.[1]??null);const registrar=all.match(/Registrar[^\n:]*[:\-]\s*([^\n]+)/i)?.[1]?.trim()??null;const about=all.match(/About[^\n]{0,80}\n?([\s\S]{80,900}?)(?:\n\n|Key People|IPO Details)/i)?.[1]?.trim()??null;const risks=(all.split(/Risk Factors/i)[1]??"").split(/\n|•/).map(clean).filter(x=>x.length>45&&x.length<400).slice(0,8);const fin=financials(find(tables,/revenue|total income|profit after tax/i));const objects=(all.split(/Objects of the Issue/i)[1]??"").split(/\n|•/).map(clean).filter(x=>x.length>20&&x.length<400).slice(0,8);const website=[...html.matchAll(/href="(https?:\/\/[^"]+)"[^>]*>\s*Visit Website/i)][0]?.[1]??null;return{priceBand:band.text,priceLow:band.low,priceHigh:band.high,lotSize:lot,listingDate:listing,business:about,registrar,registrarWebsite:website,allotmentCheckUrl:allotmentUrlForRegistrar(registrar),financials:fin,objects,risks,chittorgarhUrl:pageUrl,detailSource:"Chittorgarh",verifiedSources:["Chittorgarh"],sourceUrls:[pageUrl],verifiedAt:new Date().toISOString()};}
export async function fetchChittorgarhDetail(url:string){return cached(`chittor:detail:${url}`,600000,async()=>parseChittorgarhDetail(await fetchText(url,{timeoutMs:12000}),url));}
