import { cached } from "../cache";
import { extractLinks, parseHtmlTables, visibleText } from "../html";
import { fetchText } from "../http";
import { allotmentUrlForRegistrar } from "../registrars";
import { clean, namesMatch, normalizeCompanyName, num, parseDate, parsePriceBand } from "../text";
import type { FinancialYear, IpoRecord } from "../types";

const LIST_URL="https://www.chittorgarh.com/report/ipo-in-india-list-main-board-sme/82/";
export interface ChittorIndexItem{name:string;url:string}
export async function fetchChittorgarhIndex():Promise<ChittorIndexItem[]>{return cached("chittor:index",1800000,async()=>{const html=await fetchText(LIST_URL,{timeoutMs:12000});return extractLinks(html,/\/ipo\/[a-z0-9-]+-ipo\/\d+/i).map(l=>({name:l.text,url:l.href.startsWith("http")?l.href:`https://www.chittorgarh.com${l.href}`})).filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i);});}
export function matchChittorgarhUrl(index:ChittorIndexItem[],name:string){const hit=index.find(x=>namesMatch(x.name.replace(/ipo/gi," "),name)||namesMatch(x.url,name));if(hit)return hit.url;const slug=normalizeCompanyName(name).replace(/\s+/g,"-");return index.find(x=>x.url.includes(slug)||x.url.includes(slug.slice(0,18)))?.url??null;}
function rows(html:string){return parseHtmlTables(html);}
function find(tables:string[][][],rx:RegExp){return tables.find(t=>t.some(r=>r.some(c=>rx.test(c))))??null;}
function financials(table:string[][]|null):FinancialYear[]{if(!table||table.length<2)return[];const years=table[0].slice(1).map(clean).filter(x=>/20\d{2}|mar|dec|jan/i.test(x));const pick=(rx:RegExp)=>{const r=table.find(x=>rx.test(x[0]||""));return years.map((_,i)=>r?num(r[i+1]):null)};return years.map((year,i)=>({year,revenue:pick(/revenue|turnover|total income/i)[i],ebitda:pick(/ebitda/i)[i],pat:pick(/profit after tax|net profit|^pat$/i)[i],eps:pick(/^eps/i)[i],debt:pick(/debt|borrow/i)[i],netWorth:pick(/net worth|networth/i)[i],assets:pick(/^assets|total assets/i)[i],roe:pick(/roe|ronw|return on/i)[i],roce:pick(/roce/i)[i],source:"Chittorgarh"}));}
function labelValue(text:string,labels:RegExp[]){for(const rx of labels){const m=text.match(rx);if(m?.[1])return clean(m[1]);}return null;}
function namedList(text:string,labels:RegExp[],limit=12){for(const rx of labels){const m=text.match(rx);if(m?.[1])return m[1].split(/,|;|\\n|\\s+and\\s+/i).map(clean).filter(x=>x.length>2&&x.length<120).slice(0,limit);}return[];}
function parseIssueStructure(text:string,tables:string[][][]){let fresh:number|null=null,ofs:number|null=null;for(const t of tables){const joined=t.map(r=>r.join(" | ")).join("\n");if(!fresh){const m=joined.match(/fresh issue[^\\d]{0,80}([\\d,]+(?:\\.\\d+)?)\\s*(?:crore|cr)/i);if(m)fresh=num(m[1]);}if(!ofs){const m=joined.match(/offer for sale[^\\d]{0,80}([\\d,]+(?:\\.\\d+)?)\\s*(?:crore|cr)/i);if(m)ofs=num(m[1]);}}if(fresh==null){const m=text.match(/fresh issue[^\\d]{0,100}([\\d,]+(?:\\.\\d+)?)\\s*(?:crore|cr)/i);if(m)fresh=num(m[1]);}if(ofs==null){const m=text.match(/offer for sale[^\\d]{0,100}([\\d,]+(?:\\.\\d+)?)\\s*(?:crore|cr)/i);if(m)ofs=num(m[1]);}return{freshIssue:fresh,offerForSale:ofs};}
function parseCountries(text:string,tables:string[][][]):{countries:Array<{country:string;business:string;salesPct:number|null}>;countryCount:number|null}{const countries:Array<{country:string;business:string;salesPct:number|null}>=[];for(const table of tables){const joined=table.map(r=>r.join(" | ")).join("\n");if(!/(country|geograph|overseas|export)/i.test(joined)||!/(sales|revenue|%|percent|turnover)/i.test(joined))continue;for(const row of table.slice(1)){const cell=clean(row[0]??"");if(!cell||/^(country|geograph|total|grand total)$/i.test(cell)||cell.length>80)continue;const pctCell=row.find(x=>/%/.test(x))??"";const m=pctCell.match(/(\d+(?:\.\d+)?)\s*%/);const salesPct=m?Number(m[1]):null;if(/^[A-Za-z][A-Za-z .&'()/-]{1,70}$/.test(cell)&&!countries.some(x=>x.country.toLowerCase()===cell.toLowerCase()))countries.push({country:cell,business:"",salesPct});}}const countMatch=text.match(/(?:operate|operates|present|presence|export|exports|serves|serve)[^\n]{0,80}?(?:in|to|across|over)[^\n]{0,30}?(\d{1,3})\s+(?:countries|country)/i)??text.match(/(\d{1,3})\s+(?:countries|country)[^\n]{0,50}?(?:operate|export|presence|business)/i);const explicit=countMatch?Number(countMatch[1]):null;return{countries,countryCount:explicit??(countries.length||null)};}
function listSection(text:string,headers:RegExp,min=20,max=600,limit=12){const start=text.search(headers);if(start<0)return[];const tail=text.slice(start+1);const stop=tail.search(/\n(?:Key People|Promoters|IPO Details|Financials|Registrar|Lead Manager|Contact|Important Dates|Subscription|GMP|About Company|Business|Risk Factors|Objects of (?:the )?(?:Issue|Offer))/i);const section=stop>=0?tail.slice(0,stop):tail;return section.split(/\n|•|\d+[.)]\s+/).map(clean).filter(x=>x.length>=min&&x.length<=max).slice(0,limit);}
export function parseChittorgarhDetail(html:string,pageUrl:string):Partial<IpoRecord>{const text=visibleText(html),tables=rows(html),all=text;const band=parsePriceBand((all.match(/Price Band\s*[:\-]?\s*₹?\s*([\d,]+\s*[-–]\s*[\d,]+)/i)?.[1]??""));const lot=num(all.match(/Lot Size\s*[:\-]?\s*([\d,]+)/i)?.[1]??null),listing=parseDate(all.match(/Listing Date\s*[:\-]?\s*([A-Za-z]{3,}\s+\d{1,2},?\s+\d{4})/i)?.[1]??null);const registrar=all.match(/Registrar[^\n:]*[:\-]\s*([^\n]+)/i)?.[1]?.trim()??null;const about=(all.match(/(?:About (?:the )?Company|Company Profile|Business)[\s:\-]*([\s\S]{80,1800}?)(?=\n(?:Key People|Promoters|IPO Details|Objectives of the Issue|Objects of the Issue|Risk Factors|Financials|Registrar|$))/i)?.[1]??"").replace(/\s+/g," ").trim()||null;const risks=listSection(all,/Risk Factors|Key Risks|Risks/i,45,700,12);const countryData=parseCountries(all,tables);const structure=parseIssueStructure(all,tables);const sector=labelValue(all,[/(?:Industry|Sector|Industry\/Sector)\\s*[:\\-]\\s*([^\\n]+)/i]);const city=labelValue(all,[/(?:Registered Office|Corporate Office|Head Office|Location)\\s*[:\\-]\\s*([^\\n]+)/i]);const promoters=namedList(all,[/(?:Promoters?|Promoter Group)\\s*[:\\-]\\s*([^\\n]+)/i]);const competitors=namedList(all,[/(?:Key Competitors?|Peers|Listed Peers?)\\s*[:\\-]\\s*([^\\n]+)/i]);const segments=namedList(all,[/(?:Segments?|Business Segments?)\\s*[:\\-]\\s*([^\\n]+)/i]);const objects=listSection(all,/Objects of (?:the )?(?:Issue|Offer)|Utilisation of Proceeds/i,20,700,12);const fin=financials(find(tables,/revenue|total income|profit after tax/i));const website=[...html.matchAll(/href="(https?:\/\/[^"]+)"[^>]*>\s*Visit Website/i)][0]?.[1]??null;const revenues=fin.map(x=>({year:x.year,value:x.revenue})).filter(x=>x.value!=null);const profits=fin.map(x=>({year:x.year,value:x.pat})).filter(x=>x.value!=null);const eps=fin.map(x=>({year:x.year,value:x.eps})).filter(x=>x.value!=null);return{priceBand:band.text,priceLow:band.low,priceHigh:band.high,lotSize:lot,listingDate:listing,business:about,sector,city,promoters,competitors,segments,registrarWebsite:website,allotmentCheckUrl:allotmentUrlForRegistrar(registrar),financials:fin,revenues,profits,eps,objects,risks,countries:countryData.countries,countryCount:countryData.countryCount,freshIssue:structure.freshIssue,offerForSale:structure.offerForSale,issueType:structure.freshIssue!=null&&structure.offerForSale!=null?"Fresh Issue + Offer for Sale":structure.freshIssue!=null?"Fresh Issue":structure.offerForSale!=null?"Offer for Sale":null,chittorgarhUrl:pageUrl,detailSource:"Chittorgarh",verifiedSources:["Chittorgarh"],sourceUrls:[pageUrl],verifiedAt:new Date().toISOString()};}
export async function fetchChittorgarhDetail(url:string){return cached(`chittor:detail:${url}`,600000,async()=>parseChittorgarhDetail(await fetchText(url,{timeoutMs:12000}),url));}