import { cached } from "../cache";
import { fetchJson } from "../http";
import { setField } from "../merge";
import { allotmentUrlForRegistrar, NSE_IPO_PAGE, SEBI_PUBLIC_ISSUES } from "../registrars";
import { clean, indiaToday, isHttpUrl, num, parseDate, parsePriceBand, slugId, normalizeCompanyName } from "../text";
import { emptyIpo, type IpoRecord, type SubscriptionCategoryName, type SubscriptionRow } from "../types";

const NSE="https://www.nseindia.com";
const HEADERS={Referer:NSE_IPO_PAGE,Accept:"application/json"};
const url=(p:string)=>NSE+p;
function rows(raw:unknown):any[]{if(Array.isArray(raw))return raw.filter(Boolean);if(raw&&typeof raw==="object"){for(const v of Object.values(raw as any))if(Array.isArray(v))return v.filter(Boolean);}return[];}
function board(r:any):"Mainboard"|"SME"{const s=clean(r?.series??r?.securityType??"").toUpperCase();return s.includes("SME")?"SME":"Mainboard";}
function source(url=NSE_IPO_PAGE){return{source:"NSE India",url,timestamp:new Date().toISOString(),confidence:"official" as const};}
function derived(){return{source:"NSE India",url:NSE_IPO_PAGE,timestamp:new Date().toISOString(),confidence:"derived" as const};}
export function nseId(name:string,openDate:string|null,closeDate:string|null,symbol:string|null){return `ipo-${slugId(normalizeCompanyName(name)||symbol||"ipo")}-${slugId(openDate??closeDate??symbol??"no-date")}`;}
function fromRow(r:any,origin:"current"|"upcoming"|"past"):IpoRecord{const name=clean(r.companyName||r.company||r.symbol||"IPO"),symbol=clean(r.symbol)||null,isBse=String(r.isBse??"")==="1",openDate=parseDate(r.issueStartDate??r.ipoStartDate),closeDate=parseDate(r.issueEndDate??r.ipoEndDate),listingDate=parseDate(r.listingDate),band=parsePriceBand(r.issuePrice??r.priceRange??r.priceBand),shares=num(r.noOfSharesOffered??r.issueSize),lot=num(r.lotSize??r.bidLot),bid=num(r.noOfsharesBid??r.noOfSharesBid),reported=num(r.noOfTime??r.noOfTimes??r.subscription),sub=reported!=null?Number(reported.toFixed(2)):shares&&bid?Number((bid/shares).toFixed(2)):null,high=band.high,min=lot!=null&&high!=null?lot*high:null,issue=shares!=null&&high!=null?(shares*high)/1e7:null,amount=bid!=null&&high!=null?(bid*high)/1e7:null;const ipo=emptyIpo({id:nseId(name,openDate,closeDate,symbol),name,normalizedName:normalizeCompanyName(name),type:board(r),symbol:isBse?null:symbol,nseSymbol:isBse?null:symbol,bseSymbol:isBse?symbol:null,bseScripCode:r.scripCode?clean(r.scripCode):null,exchange:isBse?"BSE India":"NSE India",exchanges:[isBse?"BSE India":"NSE India"],openDate,closeDate,listingDate,priceBand:band.text,priceLow:band.low,priceHigh:band.high,sharesOffered:shares,lotSize:lot,subscription:sub,subscriptionAmount:amount,subscriptionSource:sub!=null?"NSE India":null,minSubscription:min,issueSize:issue,verifiedMinApplication:min,nsePageUrl:NSE_IPO_PAGE,verifiedSources:["NSE India"],sourceUrls:[NSE_IPO_PAGE],detailSource:NSE_IPO_PAGE});const src=source();for(const [k,v] of Object.entries({openDate,closeDate,listingDate,priceBand:band.text,priceLow:band.low,priceHigh:band.high,sharesOffered:shares,lotSize:lot,subscription:sub,subscriptionSource:sub!=null?"NSE India":null} as any))setField(ipo,k as keyof IpoRecord,v,src,{overwrite:true});setField(ipo,"issueSize",issue,derived());setField(ipo,"subscriptionAmount",amount,derived());setField(ipo,"minSubscription",min,derived());if(origin==="current"&&sub!=null)ipo.subscriptionTimestamp=new Date().toISOString();return ipo;}
export async function fetchNseCurrent(){return cached("nse:current",45000,async()=>rows(await fetchJson(url("/api/ipo-current-issue"),{headers:HEADERS,timeoutMs:8000})).map(r=>fromRow(r,"current")));}
export async function fetchNseUpcoming(){return cached("nse:upcoming",45000,async()=>rows(await fetchJson(url("/api/all-upcoming-issues?category=ipo"),{headers:HEADERS,timeoutMs:8000})).map(r=>fromRow(r,"upcoming")));}
export async function fetchNsePastRecent(){return cached("nse:past",600000,async()=>{const today=indiaToday();const[y,m,d]=today.split("-");const months=["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];const to=`${d}-${months[+m-1]}-${y}`;const dt=new Date(Date.UTC(+y,+m-1,+d));dt.setUTCDate(dt.getUTCDate()-45);const from=`${String(dt.getUTCDate()).padStart(2,"0")}-${months[dt.getUTCMonth()]}-${dt.getUTCFullYear()}`;return rows(await fetchJson(url(`/api/public-past-issues?from=${from}&to=${to}&index=ipo`),{headers:HEADERS,timeoutMs:12000})).map(r=>fromRow(r,"past"));});}
function info(rows:any[]){const out:Record<string,string>={};for(const r of rows){if(r?.title)out[clean(r.title)]=clean(r.value);}return out;}
function href(v:string){const m=v.match(/https?:\/\/[^\s"'<>]+/i);return m&&isHttpUrl(m[0])?m[0].replace(/[),.;]+$/,""):null;}
function cat(label:string):SubscriptionCategoryName|null{const l=label.toLowerCase();if(l.includes("total")&&!l.includes("qib")&&!l.includes("nii"))return"Total";if(l.includes("employee"))return"Employee";if(l.includes("retail")||l.includes("rii"))return"Retail";if(l.includes("more than")||l.includes("bnii"))return"bNII";if(l.includes("upto")||l.includes("up to")||l.includes("snii"))return"sNII";if(l.includes("non institutional")||l.includes("non-institutional")||/\bnii\b/.test(l)||l.includes("hni"))return"NII";if(l.includes("qualified")||/\bqib\b/.test(l))return"QIB";return null;}
function subscription(d:any,high:number|null):SubscriptionRow[]{const found=new Map<SubscriptionCategoryName,SubscriptionRow>(),ts=clean(d?.demandGraphALL?.timestamp||d?.demandDataNSE?.[0]?.timestamp)||null;for(const r of rows(d?.bidDetails)){const c=cat(clean(r.category??r.Category??""));if(!c||found.has(c))continue;const offered=num(r.noOfSharesOffered),bids=num(r.noOfsharesBid??r.noOfSharesBid),mult=num(r.noOfTime??r.noOfTimes);found.set(c,{category:c,multiple:mult??(offered&&bids?Number((bids/offered).toFixed(2)):null),offeredShares:offered,bids,amountCr:bids!=null&&high!=null?Number((bids*high/1e7).toFixed(2)):null,source:"NSE India",timestamp:ts});}return["QIB","NII","bNII","sNII","Retail","Employee","Other","Total"].filter(c=>found.has(c as any)).map(c=>found.get(c as any)!);}
export async function fetchNseDetail(symbol:string,type:"Mainboard"|"SME"):Promise<Partial<IpoRecord>|null>{return cached(`nse:detail:${symbol}:${type}`,45000,async()=>{const d=await fetchJson<any>(url(`/api/ipo-detail?symbol=${encodeURIComponent(symbol)}&series=${type==="SME"?"SME":"EQ"}`),{headers:HEADERS,timeoutMs:10000});const inf=info(d?.issueInfo?.dataList??[]),period=inf["Issue Period"]?.match(/(\d{2}-\w{3}-\d{4})\s*to\s*(\d{2}-\w{3}-\d{4})/i),band=parsePriceBand(inf["Price Range"]),lot=num((inf["Bid Lot"]||inf["Minimum Order Quantity"]||"").match(/[\d,]+/)?.[0]),face=num((inf["Face Value"]||"").match(/[\d.]+/)?.[0]),registrar=inf["Name of the Registrar"]||null,contact=inf["Contact person name number and Email id"]||"",email=contact.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]??null,phone=contact.match(/(\+?\d[\d\s-]{7,}\d)/)?.[1]?.replace(/\s+/g,"")??null,lead=(inf["Book Running Lead Managers"]||inf["Lead Managers"]||"").split(/,| and /i).map(clean).filter(Boolean),cats=subscription(d,band.high),total=cats.find(x=>x.category==="Total"),docs=[] as IpoRecord["documents"];for(const [label,key] of [["RHP","Red Herring Prospectus"],["DRHP","Draft Red Herring Prospectus"],["Prospectus","Prospectus"],["Abridged Prospectus","Abridged Prospectus"]] as const){const u=href(inf[key]||"");if(u)docs.push({label,url:u,source:"NSE India"});}return{openDate:period?parseDate(period[1]):null,closeDate:period?parseDate(period[2]):null,priceBand:band.text,priceLow:band.low,priceHigh:band.high,lotSize:lot,faceValue:face,registrar,registrarAddress:inf["Address of the Registrar"]||null,registrarEmail:email,registrarPhone:phone,allotmentCheckUrl:allotmentUrlForRegistrar(registrar),leadManagers:lead,sponsorBank:inf["Sponsor Bank"]||null,scsbListUrl:href(inf["Branches of Self Certified Syndicate Banks (SCSBs) where syndicate / sub syndicate member to submit ASBA form"]||"")||SEBI_PUBLIC_ISSUES,documents:docs,prospectusUrl:docs[0]?.url??null,prospectusType:docs[0]?.label==="RHP"?"RHP":docs[0]?.label==="DRHP"?"DRHP":docs[0]?.label==="Prospectus"?"Prospectus":docs[0]?"Abridged Prospectus":null,subscriptionCategories:cats,subscription:total?.multiple??null,subscriptionAmount:total?.amountCr??null,subscriptionSource:"NSE India",subscriptionTimestamp:total?.timestamp??null,qibShares:cats.find(x=>x.category==="QIB")?.offeredShares??null,niiShares:cats.find(x=>x.category==="NII")?.offeredShares??null,bniiShares:cats.find(x=>x.category==="bNII")?.offeredShares??null,sniiShares:cats.find(x=>x.category==="sNII")?.offeredShares??null,retailShares:cats.find(x=>x.category==="Retail")?.offeredShares??null,employeeShares:cats.find(x=>x.category==="Employee")?.offeredShares??null,nsePageUrl:NSE_IPO_PAGE,verifiedSources:["NSE India"],sourceUrls:[NSE_IPO_PAGE,...docs.map(x=>x.url)],detailSource:NSE_IPO_PAGE};});}
export function applyPatch(target:IpoRecord,patch:Partial<IpoRecord>|null,sourceName="NSE India",urlValue:string|null=NSE_IPO_PAGE){if(!patch)return target;const src={source:sourceName,url:urlValue,timestamp:new Date().toISOString(),confidence:sourceName==="NSE India"||sourceName==="BSE India"||sourceName==="SEBI"?"official" as const:"secondary" as const};for(const[k,v]of Object.entries(patch) as Array<[keyof IpoRecord,IpoRecord[keyof IpoRecord]]>){if(k==="id"||k==="name")continue;setField(target,k,v as never,src);}return target;}
